import os, sys, subprocess, glob

Import('gDebug')

try:
    itubras = os.environ['ITUBRAS']
except:
    itubras = '../../'

includePath = ['include', 'src', 'src/lua', 
itubras + '/deps/irrlicht/include']

env = Environment(CPPPATH = includePath, MSVS_VERSION='8.0')

gPlatform = Environment()['PLATFORM']

libName = 'libs/libCLSL'
LibPath = 'libs'
if gDebug:
    libName = 'libs/libCLSL_d'
libCCFlags = ''
libLNFlags = ''
if gPlatform == 'win32':
    defines = ' /D "WIN32" /D "_LIB" /D "_UNICODE" /D "UNICODE"'
    #defines = ' /D "WIN32" /D "_LIB" /D "_UNICODE" /D "UNICODE"'
    if gDebug:
        libCCFlags = '/Od /Gm /EHsc /RTC1 /MTd /W3 /c /Wp64 /ZI /TC'
        defines = defines + ' /D "_DEBUG"'
    else:
        libCCFlags = '/O2 /GL /FD /EHsc /MT /W3 /c /Wp64 /Zi /TC'
        defines = defines + ' /D "NDEBUG"'
        libLNFlags = '/LTCG'

    libCCFlags += defines
        
elif gPlatform == 'posix':
    if gDebug:
        libCCFlags = '-g'

env.Append(CCFLAGS = libCCFlags)
env.Append(LINKFLAGS = libLNFlags)

cppFiles = glob.glob('src/*.cpp')
cppFiles += ['src\lua\lapi.c',
	'src\lua\lauxlib.c',
	'src\lua\lbaselib.c',
	'src\lua\lcode.c',
	'src\lua\ldebug.c',
	'src\lua\ldo.c',
	'src\lua\ldump.c',
	'src\lua\lfunc.c',
	'src\lua\lgc.c',
	'src\lua\llex.c',
	'src\lua\lmem.c',
	'src\lua\loadlib.c',
	'src\lua\lobject.c',
	'src\lua\lopcodes.c',
	'src\lua\lparser.c',
	'src\lua\lstate.c',
	'src\lua\lstring.c',
	'src\lua\ltable.c',
	'src\lua\ltm.c',
	'src\lua\lua.c',
	'src\lua\lundump.c',
	'src\lua\lvm.c',
	'src\lua\lzio.c'
]


i = 0
for file in cppFiles:
    nfile = file.replace('src','objs')
    cppFiles[i] = nfile
    i += 1

env.Append(CLSLSourceFiles = cppFiles)

env.BuildDir('objs', 'src', duplicate=0)

Export('env')

library = env.StaticLibrary(libName,cppFiles)
Default(library)


