/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g
 *     -                            On : 2008-10-12 11:00:48
 *     -                 for the lexer : islLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "islLexer.h"
/* ----------------------------------------- */


/** String literals used by islLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x63, 0x6F, 0x6C, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x6D, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x63, 0x6F, 0x6E, 0x66, 0x69, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x2F, 0x2A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x2A, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pislLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pislLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pislLexer_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__22    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__23    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__24    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__25    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__26    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__27    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__28    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__29    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__30    (pislLexer ctx);
static ANTLR3_INLINE  void	mT__31    (pislLexer ctx);
static ANTLR3_INLINE  void	mSTRING    (pislLexer ctx);
static ANTLR3_INLINE  void	mDOT    (pislLexer ctx);
static ANTLR3_INLINE  void	mCOLON    (pislLexer ctx);
static ANTLR3_INLINE  void	mCOMMA    (pislLexer ctx);
static ANTLR3_INLINE  void	mLPAREN    (pislLexer ctx);
static ANTLR3_INLINE  void	mRPAREN    (pislLexer ctx);
static ANTLR3_INLINE  void	mINTEGER    (pislLexer ctx);
static ANTLR3_INLINE  void	mASSIGN    (pislLexer ctx);
static ANTLR3_INLINE  void	mFLOAT    (pislLexer ctx);
static ANTLR3_INLINE  void	mNAME    (pislLexer ctx);
static ANTLR3_INLINE  void	mMCMT    (pislLexer ctx);
static ANTLR3_INLINE  void	mSCMT    (pislLexer ctx);
static ANTLR3_INLINE  void	mWS    (pislLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pislLexer ctx);
static void	islLexerFree(pislLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
islLexerFree  (pislLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called islLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pislLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pislLexer islLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return islLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called islLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pislLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pislLexer islLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pislLexer ctx; // Context structure we will build and return

    ctx = (pislLexer) ANTLR3_CALLOC(1, sizeof(islLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in islLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our islLexer interface
     */
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mSTRING	= mSTRING;
    ctx->mDOT	= mDOT;
    ctx->mCOLON	= mCOLON;
    ctx->mCOMMA	= mCOMMA;
    ctx->mLPAREN	= mLPAREN;
    ctx->mRPAREN	= mRPAREN;
    ctx->mINTEGER	= mINTEGER;
    ctx->mASSIGN	= mASSIGN;
    ctx->mFLOAT	= mFLOAT;
    ctx->mNAME	= mNAME;
    ctx->mMCMT	= mMCMT;
    ctx->mSCMT	= mSCMT;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= islLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | STRING | DOT | COLON | COMMA | LPAREN | RPAREN | INTEGER | ASSIGN | FLOAT | NAME | MCMT | SCMT | WS );
 */
static const ANTLR3_INT32 dfa9_eot[44] =
    {
	17, -1, -1, 19, 19, -1, -1, -1, -1, 25, -1, 27, -1, -1, -1, -1, 17, -1, 
	-1, -1, -1, 19, 19, -1, -1, -1, -1, -1, 19, 19, 19, 19, 19, 19, 37, 19, 
	19, -1, 40, 19, -1, 19, 43, -1
    };
static const ANTLR3_INT32 dfa9_eof[44] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa9_min[44] =
    {
	9, -1, -1, 111, 97, -1, -1, -1, -1, 42, -1, 48, -1, -1, -1, -1, 46, -1, 
	-1, -1, -1, 108, 116, -1, -1, -1, -1, -1, 111, 102, 101, 114, 105, 114, 
	48, 103, 105, -1, 48, 97, -1, 108, 48, -1
    };
static const ANTLR3_INT32 dfa9_max[44] =
    {
	125, -1, -1, 111, 97, -1, -1, -1, -1, 47, -1, 57, -1, -1, -1, -1, 57, 
	-1, -1, -1, -1, 110, 116, -1, -1, -1, -1, -1, 111, 102, 101, 114, 105, 
	114, 122, 103, 105, -1, 122, 97, -1, 108, 122, -1
    };
static const ANTLR3_INT32 dfa9_accept[44] =
    {
	-1, 1, 2, -1, -1, 6, 7, 8, 9, -1, 11, -1, 13, 14, 15, 16, -1, 17, 18, 
	20, 23, -1, -1, 21, 22, 10, 19, 12, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	3, -1, -1, 5, -1, -1, 4
    };
static const ANTLR3_INT32 dfa9_special[44] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa9_T_empty	    NULL

static const ANTLR3_INT32 dfa9_T0[] =
    {
	38
    };static const ANTLR3_INT32 dfa9_T1[] =
    {
	22
    };static const ANTLR3_INT32 dfa9_T2[] =
    {
	32
    };static const ANTLR3_INT32 dfa9_T3[] =
    {
	35
    };static const ANTLR3_INT32 dfa9_T4[] =
    {
	26, -1, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16
    };static const ANTLR3_INT32 dfa9_T5[] =
    {
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, -1, -1, -1, -1, -1, -1, -1, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, 19, 19, 19, -1, -1, -1, -1, 19, -1, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19
    };static const ANTLR3_INT32 dfa9_T6[] =
    {
	39
    };static const ANTLR3_INT32 dfa9_T7[] =
    {
	36
    };static const ANTLR3_INT32 dfa9_T8[] =
    {
	33
    };static const ANTLR3_INT32 dfa9_T9[] =
    {
	30
    };static const ANTLR3_INT32 dfa9_T10[] =
    {
	42
    };static const ANTLR3_INT32 dfa9_T11[] =
    {
	26, 26, 26, 26, 26, 26, 26, 26, 26, 26
    };static const ANTLR3_INT32 dfa9_T12[] =
    {
	41
    };static const ANTLR3_INT32 dfa9_T13[] =
    {
	21
    };static const ANTLR3_INT32 dfa9_T14[] =
    {
	28, -1, 29
    };static const ANTLR3_INT32 dfa9_T15[] =
    {
	23, -1, -1, -1, -1, 24
    };static const ANTLR3_INT32 dfa9_T16[] =
    {
	31
    };static const ANTLR3_INT32 dfa9_T17[] =
    {
	34
    };static const ANTLR3_INT32 dfa9_T18[] =
    {
	20, 20, -1, -1, 20, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 20, -1, 10, -1, -1, -1, -1, 10, 14, 15, 8, 6, 13, 7, 
	11, 9, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 12, 5, -1, 18, -1, -1, -1, 
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, -1, -1, -1, -1, 19, -1, 19, 19, 3, 19, 
	19, 19, 19, 19, 19, 19, 19, 19, 4, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
	19, 19, 19, 19, 1, -1, 2
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa9_transitions[] =
{
    dfa9_T18, dfa9_T_empty, dfa9_T_empty, dfa9_T13, dfa9_T1, dfa9_T_empty, 
    dfa9_T_empty, dfa9_T_empty, dfa9_T_empty, dfa9_T15, dfa9_T_empty, dfa9_T11, 
    dfa9_T_empty, dfa9_T_empty, dfa9_T_empty, dfa9_T_empty, dfa9_T4, dfa9_T_empty, 
    dfa9_T_empty, dfa9_T_empty, dfa9_T_empty, dfa9_T14, dfa9_T9, dfa9_T_empty, 
    dfa9_T_empty, dfa9_T_empty, dfa9_T_empty, dfa9_T_empty, dfa9_T16, dfa9_T2, 
    dfa9_T8, dfa9_T17, dfa9_T3, dfa9_T7, dfa9_T5, dfa9_T0, dfa9_T6, dfa9_T_empty, 
    dfa9_T5, dfa9_T12, dfa9_T_empty, dfa9_T10, dfa9_T5, dfa9_T_empty	
};


/* Declare tracking structure for Cyclic DFA 9
 */
static
ANTLR3_CYCLIC_DFA cdfa9
    =	{
	    9,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | STRING | DOT | COLON | COMMA | LPAREN | RPAREN | INTEGER | ASSIGN | FLOAT | NAME | MCMT | SCMT | WS );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa9_eot,	    /* EOT table			    */
	    dfa9_eof,	    /* EOF table			    */
	    dfa9_min,	    /* Minimum tokens for each state    */
	    dfa9_max,	    /* Maximum tokens for each state    */
	    dfa9_accept,	/* Accept table			    */
	    dfa9_special,	/* Special transition states	    */
	    dfa9_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 9
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__22;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:7:7: ( '{' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:7:9: '{'
    {
        MATCHC('{'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 8:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__23;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:8:7: ( '}' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:8:9: '}'
    {
        MATCHC('}'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 9:7: ( 'color' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__24;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:9:7: ( 'color' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:9:9: 'color'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 10:7: ( 'material' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__25;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:10:7: ( 'material' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:10:9: 'material'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 11:7: ( 'config' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__26;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:11:7: ( 'config' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:11:9: 'config'
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 12:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__27;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:12:7: ( ';' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:12:9: ';'
    {
        MATCHC(';'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 13:7: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__28;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:13:7: ( '+' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:13:9: '+'
    {
        MATCHC('+'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 14:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__29;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:14:7: ( '-' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:14:9: '-'
    {
        MATCHC('-'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 15:7: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__30;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:15:7: ( '*' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:15:9: '*'
    {
        MATCHC('*'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 16:7: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__31;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:16:7: ( '/' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:16:9: '/'
    {
        MATCHC('/'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 69:9: ( ( '\"' ( . )* '\"' ) | ( '\\'' ( . )* '\\'' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = STRING;
       
    
    {
        //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:9: ( ( '\"' ( . )* '\"' ) | ( '\\'' ( . )* '\\'' ) )
        
        ANTLR3_UINT32 alt3;

        alt3=2;


        {
            int LA3_0 = LA(1);
            if ( (LA3_0 == '"') ) 
            {
                alt3=1;
            }
            else if ( (LA3_0 == '\'') ) 
            {
                alt3=2;
            }
            else 
            {
            
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleSTRINGEx;
            }
        }
        switch (alt3) 
        {
    	case 1:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:11: ( '\"' ( . )* '\"' )
    	    {
    	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:11: ( '\"' ( . )* '\"' )
    	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:12: '\"' ( . )* '\"'
    	        {
    	            MATCHC('"'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:16: ( . )*

    	            for (;;)
    	            {
    	                int alt1=2;
    	                {
    	                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                    */
    	                    int LA1_0 = LA(1);
    	                    if ( (LA1_0 == '"') ) 
    	                    {
    	                        alt1=2;
    	                    }
    	                    else if ( (((LA1_0 >= 0x0000) && (LA1_0 <= '!')) || ((LA1_0 >= '#') && (LA1_0 <= 0xFFFF))) ) 
    	                    {
    	                        alt1=1;
    	                    }

    	                }
    	                switch (alt1) 
    	                {
    	            	case 1:
    	            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:16: .
    	            	    {
    	            	        MATCHANY(); 
    	            	        if  (HASEXCEPTION())
    	            	        {
    	            	            goto ruleSTRINGEx;
    	            	        }


    	            	    }
    	            	    break;

    	            	default:
    	            	    goto loop1;	/* break out of the loop */
    	            	    break;
    	                }
    	            }
    	            loop1: ; /* Jump out to here if this rule does not match */

    	            MATCHC('"'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	        }


    	    }
    	    break;
    	case 2:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:26: ( '\\'' ( . )* '\\'' )
    	    {
    	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:26: ( '\\'' ( . )* '\\'' )
    	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:27: '\\'' ( . )* '\\''
    	        {
    	            MATCHC('\''); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:32: ( . )*

    	            for (;;)
    	            {
    	                int alt2=2;
    	                {
    	                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                    */
    	                    int LA2_0 = LA(1);
    	                    if ( (LA2_0 == '\'') ) 
    	                    {
    	                        alt2=2;
    	                    }
    	                    else if ( (((LA2_0 >= 0x0000) && (LA2_0 <= '&')) || ((LA2_0 >= '(') && (LA2_0 <= 0xFFFF))) ) 
    	                    {
    	                        alt2=1;
    	                    }

    	                }
    	                switch (alt2) 
    	                {
    	            	case 1:
    	            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:69:32: .
    	            	    {
    	            	        MATCHANY(); 
    	            	        if  (HASEXCEPTION())
    	            	        {
    	            	            goto ruleSTRINGEx;
    	            	        }


    	            	    }
    	            	    break;

    	            	default:
    	            	    goto loop2;	/* break out of the loop */
    	            	    break;
    	                }
    	            }
    	            loop2: ; /* Jump out to here if this rule does not match */

    	            MATCHC('\''); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	        }


    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

//   Comes from: 70:9: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DOT
 *
 * Looks to match the characters the constitute the token DOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDOT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = DOT;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:70:9: ( '.' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:70:11: '.'
    {
        MATCHC('.'); 
        if  (HASEXCEPTION())
        {
            goto ruleDOTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDOTEx; /* Prevent compiler warnings */
    ruleDOTEx: ;

}
// $ANTLR end DOT

//   Comes from: 71:9: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLON(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = COLON;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:71:9: ( ':' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:71:11: ':'
    {
        MATCHC(':'); 
        if  (HASEXCEPTION())
        {
            goto ruleCOLONEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 72:9: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMA(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = COMMA;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:72:9: ( ',' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:72:11: ','
    {
        MATCHC(','); 
        if  (HASEXCEPTION())
        {
            goto ruleCOMMAEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 73:9: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LPAREN
 *
 * Looks to match the characters the constitute the token LPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLPAREN(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = LPAREN;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:73:9: ( '(' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:73:11: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleLPARENEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLPARENEx; /* Prevent compiler warnings */
    ruleLPARENEx: ;

}
// $ANTLR end LPAREN

//   Comes from: 74:9: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RPAREN
 *
 * Looks to match the characters the constitute the token RPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRPAREN(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = RPAREN;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:74:9: ( ')' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:74:11: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleRPARENEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleRPARENEx; /* Prevent compiler warnings */
    ruleRPARENEx: ;

}
// $ANTLR end RPAREN

//   Comes from: 75:9: ( ( '0' .. '9' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INTEGER
 *
 * Looks to match the characters the constitute the token INTEGER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINTEGER(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = INTEGER;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:75:9: ( ( '0' .. '9' )* )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:75:11: ( '0' .. '9' )*
    {

        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:75:11: ( '0' .. '9' )*

        for (;;)
        {
            int alt4=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA4_0 = LA(1);
                if ( (((LA4_0 >= '0') && (LA4_0 <= '9'))) ) 
                {
                    alt4=1;
                }

            }
            switch (alt4) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:75:12: '0' .. '9'
        	    {
        	        MATCHRANGE('0', '9'); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEGEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop4;	/* break out of the loop */
        	    break;
            }
        }
        loop4: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINTEGEREx; /* Prevent compiler warnings */
    ruleINTEGEREx: ;

}
// $ANTLR end INTEGER

//   Comes from: 76:9: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ASSIGN
 *
 * Looks to match the characters the constitute the token ASSIGN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mASSIGN(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = ASSIGN;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:76:9: ( '=' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:76:11: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleASSIGNEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleASSIGNEx; /* Prevent compiler warnings */
    ruleASSIGNEx: ;

}
// $ANTLR end ASSIGN

//   Comes from: 78:9: ( INTEGER '.' INTEGER )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FLOAT
 *
 * Looks to match the characters the constitute the token FLOAT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFLOAT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = FLOAT;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:78:9: ( INTEGER '.' INTEGER )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:78:11: INTEGER '.' INTEGER
    {
        /* 78:11: INTEGER '.' INTEGER */
        mINTEGER(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleFLOATEx;
        }

        MATCHC('.'); 
        if  (HASEXCEPTION())
        {
            goto ruleFLOATEx;
        }

        /* 78:11: INTEGER '.' INTEGER */
        mINTEGER(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleFLOATEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleFLOATEx; /* Prevent compiler warnings */
    ruleFLOATEx: ;

}
// $ANTLR end FLOAT

//   Comes from: 80:9: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NAME
 *
 * Looks to match the characters the constitute the token NAME
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNAME(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = NAME;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:80:9: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:80:11: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleNAMEEx;
        }


        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:80:38: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt5=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA5_0 = LA(1);
                if ( (((LA5_0 >= '0') && (LA5_0 <= '9')) || ((LA5_0 >= 'A') && (LA5_0 <= 'Z')) || LA5_0 == '_' || ((LA5_0 >= 'a') && (LA5_0 <= 'z'))) ) 
                {
                    alt5=1;
                }

            }
            switch (alt5) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleNAMEEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop5;	/* break out of the loop */
        	    break;
            }
        }
        loop5: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleNAMEEx; /* Prevent compiler warnings */
    ruleNAMEEx: ;

}
// $ANTLR end NAME

//   Comes from: 82:9: ( '/*' ( . )* '*/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MCMT
 *
 * Looks to match the characters the constitute the token MCMT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMCMT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = MCMT;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:82:9: ( '/*' ( . )* '*/' )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:82:11: '/*' ( . )* '*/'
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto ruleMCMTEx;
        }



        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:82:16: ( . )*

        for (;;)
        {
            int alt6=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA6_0 = LA(1);
                if ( (LA6_0 == '*') ) 
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA6_1 = LA(2);
                        if ( (LA6_1 == '/') ) 
                        {
                            alt6=2;
                        }
                        else if ( (((LA6_1 >= 0x0000) && (LA6_1 <= '.')) || ((LA6_1 >= '0') && (LA6_1 <= 0xFFFF))) ) 
                        {
                            alt6=1;
                        }

                    }
                }
                else if ( (((LA6_0 >= 0x0000) && (LA6_0 <= ')')) || ((LA6_0 >= '+') && (LA6_0 <= 0xFFFF))) ) 
                {
                    alt6=1;
                }

            }
            switch (alt6) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:82:16: .
        	    {
        	        MATCHANY(); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleMCMTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop6;	/* break out of the loop */
        	    break;
            }
        }
        loop6: ; /* Jump out to here if this rule does not match */

        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleMCMTEx;
        }


        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMCMTEx; /* Prevent compiler warnings */
    ruleMCMTEx: ;

}
// $ANTLR end MCMT

//   Comes from: 83:9: ( '//' (~ ( '\\n' | '\\r' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SCMT
 *
 * Looks to match the characters the constitute the token SCMT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSCMT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = SCMT;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:83:9: ( '//' (~ ( '\\n' | '\\r' ) )* )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:83:11: '//' (~ ( '\\n' | '\\r' ) )*
    {
        MATCHS(lit_6); 
        if  (HASEXCEPTION())
        {
            goto ruleSCMTEx;
        }



        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:83:16: (~ ( '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt7=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA7_0 = LA(1);
                if ( (((LA7_0 >= 0x0000) && (LA7_0 <= '\t')) || ((LA7_0 >= 0x000B) && (LA7_0 <= '\f')) || ((LA7_0 >= 0x000E) && (LA7_0 <= 0xFFFF))) ) 
                {
                    alt7=1;
                }

            }
            switch (alt7) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:83:17: ~ ( '\\n' | '\\r' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleSCMTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop7;	/* break out of the loop */
        	    break;
            }
        }
        loop7: ; /* Jump out to here if this rule does not match */

        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSCMTEx; /* Prevent compiler warnings */
    ruleSCMTEx: ;

}
// $ANTLR end SCMT

//   Comes from: 84:9: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = WS;
       
    
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:84:9: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:84:11: ( ' ' | '\\t' | '\\r' | '\\n' )+
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:84:11: ( ' ' | '\\t' | '\\r' | '\\n' )+
        {
            int cnt8=0;

            for (;;)
            {
                int alt8=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA8_0 = LA(1);
        	    if ( (((LA8_0 >= '\t') && (LA8_0 <= '\n')) || LA8_0 == '\r' || LA8_0 == ' ') ) 
        	    {
        	        alt8=1;
        	    }

        	}
        	switch (alt8) 
        	{
        	    case 1:
        	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt8 >= 1 )
        		{
        		    goto loop8;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt8++;
            }
            loop8: ;	/* Jump to here if this rule does not match */
        }
        {
             LEXSTATE->channel = HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pislLexer ctx)
{
    {
        //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:8: ( T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | STRING | DOT | COLON | COMMA | LPAREN | RPAREN | INTEGER | ASSIGN | FLOAT | NAME | MCMT | SCMT | WS )
        
        ANTLR3_UINT32 alt9;

        alt9=23;

        alt9 = cdfa9.predict(ctx, RECOGNIZER, ISTREAM, &cdfa9);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt9) 
        {
    	case 1:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:10: T__22
    	    {
    	        /* 1:10: T__22 */
    	        mT__22(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:16: T__23
    	    {
    	        /* 1:16: T__23 */
    	        mT__23(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:22: T__24
    	    {
    	        /* 1:22: T__24 */
    	        mT__24(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:28: T__25
    	    {
    	        /* 1:28: T__25 */
    	        mT__25(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:34: T__26
    	    {
    	        /* 1:34: T__26 */
    	        mT__26(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:40: T__27
    	    {
    	        /* 1:40: T__27 */
    	        mT__27(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:46: T__28
    	    {
    	        /* 1:46: T__28 */
    	        mT__28(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:52: T__29
    	    {
    	        /* 1:52: T__29 */
    	        mT__29(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:58: T__30
    	    {
    	        /* 1:58: T__30 */
    	        mT__30(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:64: T__31
    	    {
    	        /* 1:64: T__31 */
    	        mT__31(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:70: STRING
    	    {
    	        /* 1:70: STRING */
    	        mSTRING(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:77: DOT
    	    {
    	        /* 1:77: DOT */
    	        mDOT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:81: COLON
    	    {
    	        /* 1:81: COLON */
    	        mCOLON(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:87: COMMA
    	    {
    	        /* 1:87: COMMA */
    	        mCOMMA(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:93: LPAREN
    	    {
    	        /* 1:93: LPAREN */
    	        mLPAREN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:100: RPAREN
    	    {
    	        /* 1:100: RPAREN */
    	        mRPAREN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:107: INTEGER
    	    {
    	        /* 1:107: INTEGER */
    	        mINTEGER(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:115: ASSIGN
    	    {
    	        /* 1:115: ASSIGN */
    	        mASSIGN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:122: FLOAT
    	    {
    	        /* 1:122: FLOAT */
    	        mFLOAT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:128: NAME
    	    {
    	        /* 1:128: NAME */
    	        mNAME(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:133: MCMT
    	    {
    	        /* 1:133: MCMT */
    	        mMCMT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:138: SCMT
    	    {
    	        /* 1:138: SCMT */
    	        mSCMT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:1:143: WS
    	    {
    	        /* 1:143: WS */
    	        mWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
