gDebug = True
if int(ARGUMENTS.get('release',0)):
    gDebug = False

Help("""
 Build Arguments/Options:
    release=1           Builds the release verion.
      """)    

Export('gDebug')

SConscript(['SConscript'])
