/*
 * Interface header file.
 *
 * Generated by SIP 4.6 (4.6) on Sat Apr 14 23:44:11 2007
 */

#ifndef _TubrasTString_h
#define _TubrasTString_h



#line 22 "Tubras.sip"
#include <string>
#line 15 "sipTubrasTString.h"

#define sipMappedType_TString        &sipMappedTypeDef_TString
#define sipForceConvertTo_TString    sipMappedTypeDef_TString.mt_fcto
#define sipConvertFrom_TString       sipMappedTypeDef_TString.mt_cfrom

extern sipMappedType sipMappedTypeDef_TString;

#endif
