/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g
 *     -                            On : 2008-10-13 13:28:37
 *     -                 for the lexer : islLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "islLexer.h"
/* ----------------------------------------- */


/** String literals used by islLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x54, 0x52, 0x55, 0x45,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x54, 0x72, 0x75, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x74, 0x72, 0x75, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x46, 0x41, 0x4C, 0x53, 0x45,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x46, 0x61, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x66, 0x61, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x63, 0x6F, 0x6C, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x6D, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x63, 0x6F, 0x6E, 0x66, 0x69, 0x67,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x2F, 0x2A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x2A, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pislLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pislLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pislLexer_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__31    (pislLexer ctx);
static ANTLR3_INLINE  void	mSTRING    (pislLexer ctx);
static ANTLR3_INLINE  void	mDOT    (pislLexer ctx);
static ANTLR3_INLINE  void	mCOLON    (pislLexer ctx);
static ANTLR3_INLINE  void	mCOMMA    (pislLexer ctx);
static ANTLR3_INLINE  void	mLPAREN    (pislLexer ctx);
static ANTLR3_INLINE  void	mRPAREN    (pislLexer ctx);
static ANTLR3_INLINE  void	mINTEGER    (pislLexer ctx);
static ANTLR3_INLINE  void	mBTRUE    (pislLexer ctx);
static ANTLR3_INLINE  void	mBFALSE    (pislLexer ctx);
static ANTLR3_INLINE  void	mASSIGN    (pislLexer ctx);
static ANTLR3_INLINE  void	mADD    (pislLexer ctx);
static ANTLR3_INLINE  void	mSUB    (pislLexer ctx);
static ANTLR3_INLINE  void	mMUL    (pislLexer ctx);
static ANTLR3_INLINE  void	mDIV    (pislLexer ctx);
static ANTLR3_INLINE  void	mSTARTDEF    (pislLexer ctx);
static ANTLR3_INLINE  void	mENDDEF    (pislLexer ctx);
static ANTLR3_INLINE  void	mCOLDEF    (pislLexer ctx);
static ANTLR3_INLINE  void	mMATDEF    (pislLexer ctx);
static ANTLR3_INLINE  void	mCNFDEF    (pislLexer ctx);
static ANTLR3_INLINE  void	mFLOAT    (pislLexer ctx);
static ANTLR3_INLINE  void	mNAME    (pislLexer ctx);
static ANTLR3_INLINE  void	mMCMT    (pislLexer ctx);
static ANTLR3_INLINE  void	mSCMT    (pislLexer ctx);
static ANTLR3_INLINE  void	mWS    (pislLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pislLexer ctx);
static void	islLexerFree(pislLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
islLexerFree  (pislLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called islLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pislLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pislLexer islLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return islLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called islLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pislLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pislLexer islLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pislLexer ctx; // Context structure we will build and return

    ctx = (pislLexer) ANTLR3_CALLOC(1, sizeof(islLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in islLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our islLexer interface
     */
    ctx->mT__31	= mT__31;
    ctx->mSTRING	= mSTRING;
    ctx->mDOT	= mDOT;
    ctx->mCOLON	= mCOLON;
    ctx->mCOMMA	= mCOMMA;
    ctx->mLPAREN	= mLPAREN;
    ctx->mRPAREN	= mRPAREN;
    ctx->mINTEGER	= mINTEGER;
    ctx->mBTRUE	= mBTRUE;
    ctx->mBFALSE	= mBFALSE;
    ctx->mASSIGN	= mASSIGN;
    ctx->mADD	= mADD;
    ctx->mSUB	= mSUB;
    ctx->mMUL	= mMUL;
    ctx->mDIV	= mDIV;
    ctx->mSTARTDEF	= mSTARTDEF;
    ctx->mENDDEF	= mENDDEF;
    ctx->mCOLDEF	= mCOLDEF;
    ctx->mMATDEF	= mMATDEF;
    ctx->mCNFDEF	= mCNFDEF;
    ctx->mFLOAT	= mFLOAT;
    ctx->mNAME	= mNAME;
    ctx->mMCMT	= mMCMT;
    ctx->mSCMT	= mSCMT;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= islLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__31 | STRING | DOT | COLON | COMMA | LPAREN | RPAREN | INTEGER | BTRUE | BFALSE | ASSIGN | ADD | SUB | MUL | DIV | STARTDEF | ENDDEF | COLDEF | MATDEF | CNFDEF | FLOAT | NAME | MCMT | SCMT | WS );
 */
static const ANTLR3_INT32 dfa11_eot[71] =
    {
	9, -1, -1, 25, -1, -1, -1, -1, 9, -1, 23, 23, 23, 23, -1, -1, -1, -1, 
	35, -1, -1, 23, 23, -1, -1, -1, -1, 23, 23, 23, 23, 23, 23, -1, -1, -1, 
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 56, 56, 56, 23, 23, 23, 23, 
	23, 23, -1, 63, 63, 63, 64, 23, 23, -1, -1, 67, 23, -1, 23, 70, -1
    };
static const ANTLR3_INT32 dfa11_eof[71] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_min[71] =
    {
	9, -1, -1, 48, -1, -1, -1, -1, 46, -1, 82, 114, 65, 97, -1, -1, -1, -1, 
	42, -1, -1, 111, 97, -1, -1, -1, -1, 85, 117, 117, 76, 108, 108, -1, -1, 
	-1, 108, 116, 69, 101, 101, 83, 115, 115, 111, 102, 101, 48, 48, 48, 69, 
	101, 101, 114, 105, 114, -1, 48, 48, 48, 48, 103, 105, -1, -1, 48, 97, 
	-1, 108, 48, -1
    };
static const ANTLR3_INT32 dfa11_max[71] =
    {
	125, -1, -1, 57, -1, -1, -1, -1, 57, -1, 114, 114, 97, 97, -1, -1, -1, 
	-1, 47, -1, -1, 111, 97, -1, -1, -1, -1, 85, 117, 117, 76, 108, 108, -1, 
	-1, -1, 110, 116, 69, 101, 101, 83, 115, 115, 111, 102, 101, 122, 122, 
	122, 69, 101, 101, 114, 105, 114, -1, 122, 122, 122, 122, 103, 105, -1, 
	-1, 122, 97, -1, 108, 122, -1
    };
static const ANTLR3_INT32 dfa11_accept[71] =
    {
	-1, 1, 2, -1, 4, 5, 6, 7, -1, 8, -1, -1, -1, -1, 11, 12, 13, 14, -1, 16, 
	17, -1, -1, 22, 25, 3, 21, -1, -1, -1, -1, -1, -1, 23, 24, 15, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	9, -1, -1, -1, -1, -1, -1, 10, 18, -1, -1, 20, -1, -1, 19
    };
static const ANTLR3_INT32 dfa11_special[71] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa11_T_empty	    NULL

static const ANTLR3_INT32 dfa11_T0[] =
    {
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, -1, -1, -1, -1, 23, 
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
	23, 23, 23, 23, 23, 23, 23, -1, -1, -1, -1, 23, -1, 23, 23, 23, 23, 23, 
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
	23, 23, 23
    };static const ANTLR3_INT32 dfa11_T1[] =
    {
	24, 24, -1, -1, 24, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 24, -1, 2, -1, -1, -1, -1, 2, 6, 7, 17, 15, 5, 16, 
	3, 18, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 1, -1, 14, -1, -1, -1, 23, 23, 
	23, 23, 23, 12, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 
	23, 23, 23, 23, 23, 23, -1, -1, -1, -1, 23, -1, 23, 23, 21, 23, 23, 13, 
	23, 23, 23, 23, 23, 23, 22, 23, 23, 23, 23, 23, 23, 11, 23, 23, 23, 23, 
	23, 23, 19, -1, 20
    };static const ANTLR3_INT32 dfa11_T2[] =
    {
	47
    };static const ANTLR3_INT32 dfa11_T3[] =
    {
	38
    };static const ANTLR3_INT32 dfa11_T4[] =
    {
	33, -1, -1, -1, -1, 34
    };static const ANTLR3_INT32 dfa11_T5[] =
    {
	48
    };static const ANTLR3_INT32 dfa11_T6[] =
    {
	44, -1, 45
    };static const ANTLR3_INT32 dfa11_T7[] =
    {
	39
    };static const ANTLR3_INT32 dfa11_T8[] =
    {
	40
    };static const ANTLR3_INT32 dfa11_T9[] =
    {
	49
    };static const ANTLR3_INT32 dfa11_T10[] =
    {
	27, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28
    };static const ANTLR3_INT32 dfa11_T11[] =
    {
	29
    };static const ANTLR3_INT32 dfa11_T12[] =
    {
	61
    };static const ANTLR3_INT32 dfa11_T13[] =
    {
	65
    };static const ANTLR3_INT32 dfa11_T14[] =
    {
	54
    };static const ANTLR3_INT32 dfa11_T15[] =
    {
	69
    };static const ANTLR3_INT32 dfa11_T16[] =
    {
	66
    };static const ANTLR3_INT32 dfa11_T17[] =
    {
	68
    };static const ANTLR3_INT32 dfa11_T18[] =
    {
	46
    };static const ANTLR3_INT32 dfa11_T19[] =
    {
	62
    };static const ANTLR3_INT32 dfa11_T20[] =
    {
	55
    };static const ANTLR3_INT32 dfa11_T21[] =
    {
	60
    };static const ANTLR3_INT32 dfa11_T22[] =
    {
	30, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 31
    };static const ANTLR3_INT32 dfa11_T23[] =
    {
	53
    };static const ANTLR3_INT32 dfa11_T24[] =
    {
	36
    };static const ANTLR3_INT32 dfa11_T25[] =
    {
	32
    };static const ANTLR3_INT32 dfa11_T26[] =
    {
	26, 26, 26, 26, 26, 26, 26, 26, 26, 26
    };static const ANTLR3_INT32 dfa11_T27[] =
    {
	37
    };static const ANTLR3_INT32 dfa11_T28[] =
    {
	52
    };static const ANTLR3_INT32 dfa11_T29[] =
    {
	59
    };static const ANTLR3_INT32 dfa11_T30[] =
    {
	43
    };static const ANTLR3_INT32 dfa11_T31[] =
    {
	51
    };static const ANTLR3_INT32 dfa11_T32[] =
    {
	58
    };static const ANTLR3_INT32 dfa11_T33[] =
    {
	42
    };static const ANTLR3_INT32 dfa11_T34[] =
    {
	50
    };static const ANTLR3_INT32 dfa11_T35[] =
    {
	57
    };static const ANTLR3_INT32 dfa11_T36[] =
    {
	26, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };static const ANTLR3_INT32 dfa11_T37[] =
    {
	41
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa11_transitions[] =
{
    dfa11_T1, dfa11_T_empty, dfa11_T_empty, dfa11_T26, dfa11_T_empty, dfa11_T_empty, 
    dfa11_T_empty, dfa11_T_empty, dfa11_T36, dfa11_T_empty, dfa11_T10, dfa11_T11, 
    dfa11_T22, dfa11_T25, dfa11_T_empty, dfa11_T_empty, dfa11_T_empty, dfa11_T_empty, 
    dfa11_T4, dfa11_T_empty, dfa11_T_empty, dfa11_T24, dfa11_T27, dfa11_T_empty, 
    dfa11_T_empty, dfa11_T_empty, dfa11_T_empty, dfa11_T3, dfa11_T7, dfa11_T8, 
    dfa11_T37, dfa11_T33, dfa11_T30, dfa11_T_empty, dfa11_T_empty, dfa11_T_empty, 
    dfa11_T6, dfa11_T18, dfa11_T2, dfa11_T5, dfa11_T9, dfa11_T34, dfa11_T31, 
    dfa11_T28, dfa11_T23, dfa11_T14, dfa11_T20, dfa11_T0, dfa11_T0, dfa11_T0, 
    dfa11_T35, dfa11_T32, dfa11_T29, dfa11_T21, dfa11_T12, dfa11_T19, dfa11_T_empty, 
    dfa11_T0, dfa11_T0, dfa11_T0, dfa11_T0, dfa11_T13, dfa11_T16, dfa11_T_empty, 
    dfa11_T_empty, dfa11_T0, dfa11_T17, dfa11_T_empty, dfa11_T15, dfa11_T0, 
    dfa11_T_empty	
};


/* Declare tracking structure for Cyclic DFA 11
 */
static
ANTLR3_CYCLIC_DFA cdfa11
    =	{
	    11,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__31 | STRING | DOT | COLON | COMMA | LPAREN | RPAREN | INTEGER | BTRUE | BFALSE | ASSIGN | ADD | SUB | MUL | DIV | STARTDEF | ENDDEF | COLDEF | MATDEF | CNFDEF | FLOAT | NAME | MCMT | SCMT | WS );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa11_eot,	    /* EOT table			    */
	    dfa11_eof,	    /* EOF table			    */
	    dfa11_min,	    /* Minimum tokens for each state    */
	    dfa11_max,	    /* Maximum tokens for each state    */
	    dfa11_accept,	/* Accept table			    */
	    dfa11_special,	/* Special transition states	    */
	    dfa11_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 11
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = T__31;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:7:7: ( ';' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:7:9: ';'
    {
        MATCHC(';'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 74:9: ( ( '\"' ( . )* '\"' ) | ( '\\'' ( . )* '\\'' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = STRING;
       
    
    {
        //  C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:9: ( ( '\"' ( . )* '\"' ) | ( '\\'' ( . )* '\\'' ) )
        
        ANTLR3_UINT32 alt3;

        alt3=2;


        {
            int LA3_0 = LA(1);
            if ( (LA3_0 == '"') ) 
            {
                alt3=1;
            }
            else if ( (LA3_0 == '\'') ) 
            {
                alt3=2;
            }
            else 
            {
            
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleSTRINGEx;
            }
        }
        switch (alt3) 
        {
    	case 1:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:11: ( '\"' ( . )* '\"' )
    	    {
    	        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:11: ( '\"' ( . )* '\"' )
    	        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:12: '\"' ( . )* '\"'
    	        {
    	            MATCHC('"'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	            // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:16: ( . )*

    	            for (;;)
    	            {
    	                int alt1=2;
    	                {
    	                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                    */
    	                    int LA1_0 = LA(1);
    	                    if ( (LA1_0 == '"') ) 
    	                    {
    	                        alt1=2;
    	                    }
    	                    else if ( (((LA1_0 >= 0x0000) && (LA1_0 <= '!')) || ((LA1_0 >= '#') && (LA1_0 <= 0xFFFF))) ) 
    	                    {
    	                        alt1=1;
    	                    }

    	                }
    	                switch (alt1) 
    	                {
    	            	case 1:
    	            	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:16: .
    	            	    {
    	            	        MATCHANY(); 
    	            	        if  (HASEXCEPTION())
    	            	        {
    	            	            goto ruleSTRINGEx;
    	            	        }


    	            	    }
    	            	    break;

    	            	default:
    	            	    goto loop1;	/* break out of the loop */
    	            	    break;
    	                }
    	            }
    	            loop1: ; /* Jump out to here if this rule does not match */

    	            MATCHC('"'); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	        }


    	    }
    	    break;
    	case 2:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:26: ( '\\'' ( . )* '\\'' )
    	    {
    	        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:26: ( '\\'' ( . )* '\\'' )
    	        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:27: '\\'' ( . )* '\\''
    	        {
    	            MATCHC('\''); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	            // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:32: ( . )*

    	            for (;;)
    	            {
    	                int alt2=2;
    	                {
    	                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
    	                    */
    	                    int LA2_0 = LA(1);
    	                    if ( (LA2_0 == '\'') ) 
    	                    {
    	                        alt2=2;
    	                    }
    	                    else if ( (((LA2_0 >= 0x0000) && (LA2_0 <= '&')) || ((LA2_0 >= '(') && (LA2_0 <= 0xFFFF))) ) 
    	                    {
    	                        alt2=1;
    	                    }

    	                }
    	                switch (alt2) 
    	                {
    	            	case 1:
    	            	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:74:32: .
    	            	    {
    	            	        MATCHANY(); 
    	            	        if  (HASEXCEPTION())
    	            	        {
    	            	            goto ruleSTRINGEx;
    	            	        }


    	            	    }
    	            	    break;

    	            	default:
    	            	    goto loop2;	/* break out of the loop */
    	            	    break;
    	                }
    	            }
    	            loop2: ; /* Jump out to here if this rule does not match */

    	            MATCHC('\''); 
    	            if  (HASEXCEPTION())
    	            {
    	                goto ruleSTRINGEx;
    	            }


    	        }


    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

//   Comes from: 75:9: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DOT
 *
 * Looks to match the characters the constitute the token DOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDOT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = DOT;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:75:9: ( '.' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:75:11: '.'
    {
        MATCHC('.'); 
        if  (HASEXCEPTION())
        {
            goto ruleDOTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDOTEx; /* Prevent compiler warnings */
    ruleDOTEx: ;

}
// $ANTLR end DOT

//   Comes from: 76:9: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLON(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = COLON;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:76:9: ( ':' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:76:11: ':'
    {
        MATCHC(':'); 
        if  (HASEXCEPTION())
        {
            goto ruleCOLONEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 77:9: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMA(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = COMMA;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:77:9: ( ',' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:77:11: ','
    {
        MATCHC(','); 
        if  (HASEXCEPTION())
        {
            goto ruleCOMMAEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 78:9: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LPAREN
 *
 * Looks to match the characters the constitute the token LPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLPAREN(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = LPAREN;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:78:9: ( '(' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:78:11: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleLPARENEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLPARENEx; /* Prevent compiler warnings */
    ruleLPARENEx: ;

}
// $ANTLR end LPAREN

//   Comes from: 79:9: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RPAREN
 *
 * Looks to match the characters the constitute the token RPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRPAREN(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = RPAREN;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:79:9: ( ')' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:79:11: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleRPARENEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleRPARENEx; /* Prevent compiler warnings */
    ruleRPARENEx: ;

}
// $ANTLR end RPAREN

//   Comes from: 80:9: ( ( '0' .. '9' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INTEGER
 *
 * Looks to match the characters the constitute the token INTEGER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINTEGER(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = INTEGER;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:80:9: ( ( '0' .. '9' )* )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:80:11: ( '0' .. '9' )*
    {

        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:80:11: ( '0' .. '9' )*

        for (;;)
        {
            int alt4=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA4_0 = LA(1);
                if ( (((LA4_0 >= '0') && (LA4_0 <= '9'))) ) 
                {
                    alt4=1;
                }

            }
            switch (alt4) 
            {
        	case 1:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:80:12: '0' .. '9'
        	    {
        	        MATCHRANGE('0', '9'); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEGEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop4;	/* break out of the loop */
        	    break;
            }
        }
        loop4: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleINTEGEREx; /* Prevent compiler warnings */
    ruleINTEGEREx: ;

}
// $ANTLR end INTEGER

//   Comes from: 81:10: ( ( 'TRUE' | 'True' | 'true' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BTRUE
 *
 * Looks to match the characters the constitute the token BTRUE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBTRUE(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BTRUE;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:81:10: ( ( 'TRUE' | 'True' | 'true' ) )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:81:12: ( 'TRUE' | 'True' | 'true' )
    {

        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:81:12: ( 'TRUE' | 'True' | 'true' )
        {
            int alt5=3;

            {
                int LA5_0 = LA(1);
                if ( (LA5_0 == 'T') ) 
                {

                    {
                        int LA5_1 = LA(2);
                        if ( (LA5_1 == 'R') ) 
                        {
                            alt5=1;
                        }
                        else if ( (LA5_1 == 'r') ) 
                        {
                            alt5=2;
                        }
                        else 
                        {
                        
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 5;
                            EXCEPTION->state        = 1;


                            goto ruleBTRUEEx;
                        }
                    }
                }
                else if ( (LA5_0 == 't') ) 
                {
                    alt5=3;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 5;
                    EXCEPTION->state        = 0;


                    goto ruleBTRUEEx;
                }
            }
            switch (alt5) 
            {
        	case 1:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:81:13: 'TRUE'
        	    {
        	        MATCHS(lit_1); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBTRUEEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:81:22: 'True'
        	    {
        	        MATCHS(lit_2); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBTRUEEx;
        	        }



        	    }
        	    break;
        	case 3:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:81:31: 'true'
        	    {
        	        MATCHS(lit_3); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBTRUEEx;
        	        }



        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBTRUEEx; /* Prevent compiler warnings */
    ruleBTRUEEx: ;

}
// $ANTLR end BTRUE

//   Comes from: 82:10: ( ( 'FALSE' | 'False' | 'false' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BFALSE
 *
 * Looks to match the characters the constitute the token BFALSE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBFALSE(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = BFALSE;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:82:10: ( ( 'FALSE' | 'False' | 'false' ) )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:82:12: ( 'FALSE' | 'False' | 'false' )
    {

        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:82:12: ( 'FALSE' | 'False' | 'false' )
        {
            int alt6=3;

            {
                int LA6_0 = LA(1);
                if ( (LA6_0 == 'F') ) 
                {

                    {
                        int LA6_1 = LA(2);
                        if ( (LA6_1 == 'A') ) 
                        {
                            alt6=1;
                        }
                        else if ( (LA6_1 == 'a') ) 
                        {
                            alt6=2;
                        }
                        else 
                        {
                        
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 6;
                            EXCEPTION->state        = 1;


                            goto ruleBFALSEEx;
                        }
                    }
                }
                else if ( (LA6_0 == 'f') ) 
                {
                    alt6=3;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 6;
                    EXCEPTION->state        = 0;


                    goto ruleBFALSEEx;
                }
            }
            switch (alt6) 
            {
        	case 1:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:82:13: 'FALSE'
        	    {
        	        MATCHS(lit_4); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBFALSEEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:82:23: 'False'
        	    {
        	        MATCHS(lit_5); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBFALSEEx;
        	        }



        	    }
        	    break;
        	case 3:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:82:33: 'false'
        	    {
        	        MATCHS(lit_6); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBFALSEEx;
        	        }



        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleBFALSEEx; /* Prevent compiler warnings */
    ruleBFALSEEx: ;

}
// $ANTLR end BFALSE

//   Comes from: 83:9: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ASSIGN
 *
 * Looks to match the characters the constitute the token ASSIGN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mASSIGN(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = ASSIGN;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:83:9: ( '=' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:83:11: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleASSIGNEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleASSIGNEx; /* Prevent compiler warnings */
    ruleASSIGNEx: ;

}
// $ANTLR end ASSIGN

//   Comes from: 84:9: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ADD
 *
 * Looks to match the characters the constitute the token ADD
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mADD(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = ADD;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:84:9: ( '+' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:84:11: '+'
    {
        MATCHC('+'); 
        if  (HASEXCEPTION())
        {
            goto ruleADDEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleADDEx; /* Prevent compiler warnings */
    ruleADDEx: ;

}
// $ANTLR end ADD

//   Comes from: 85:9: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SUB
 *
 * Looks to match the characters the constitute the token SUB
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSUB(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = SUB;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:85:9: ( '-' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:85:11: '-'
    {
        MATCHC('-'); 
        if  (HASEXCEPTION())
        {
            goto ruleSUBEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSUBEx; /* Prevent compiler warnings */
    ruleSUBEx: ;

}
// $ANTLR end SUB

//   Comes from: 86:9: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MUL
 *
 * Looks to match the characters the constitute the token MUL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMUL(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = MUL;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:86:9: ( '*' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:86:11: '*'
    {
        MATCHC('*'); 
        if  (HASEXCEPTION())
        {
            goto ruleMULEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMULEx; /* Prevent compiler warnings */
    ruleMULEx: ;

}
// $ANTLR end MUL

//   Comes from: 87:9: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIV
 *
 * Looks to match the characters the constitute the token DIV
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIV(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = DIV;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:87:9: ( '/' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:87:11: '/'
    {
        MATCHC('/'); 
        if  (HASEXCEPTION())
        {
            goto ruleDIVEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDIVEx; /* Prevent compiler warnings */
    ruleDIVEx: ;

}
// $ANTLR end DIV

//   Comes from: 88:10: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STARTDEF
 *
 * Looks to match the characters the constitute the token STARTDEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTARTDEF(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = STARTDEF;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:88:10: ( '{' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:88:12: '{'
    {
        MATCHC('{'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTARTDEFEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTARTDEFEx; /* Prevent compiler warnings */
    ruleSTARTDEFEx: ;

}
// $ANTLR end STARTDEF

//   Comes from: 89:8: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ENDDEF
 *
 * Looks to match the characters the constitute the token ENDDEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mENDDEF(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = ENDDEF;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:89:8: ( '}' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:89:10: '}'
    {
        MATCHC('}'); 
        if  (HASEXCEPTION())
        {
            goto ruleENDDEFEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleENDDEFEx; /* Prevent compiler warnings */
    ruleENDDEFEx: ;

}
// $ANTLR end ENDDEF

//   Comes from: 91:9: ( 'color' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLDEF
 *
 * Looks to match the characters the constitute the token COLDEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLDEF(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = COLDEF;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:91:9: ( 'color' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:91:11: 'color'
    {
        MATCHS(lit_7); 
        if  (HASEXCEPTION())
        {
            goto ruleCOLDEFEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOLDEFEx; /* Prevent compiler warnings */
    ruleCOLDEFEx: ;

}
// $ANTLR end COLDEF

//   Comes from: 92:9: ( 'material' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MATDEF
 *
 * Looks to match the characters the constitute the token MATDEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMATDEF(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = MATDEF;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:92:9: ( 'material' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:92:11: 'material'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleMATDEFEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMATDEFEx; /* Prevent compiler warnings */
    ruleMATDEFEx: ;

}
// $ANTLR end MATDEF

//   Comes from: 93:9: ( 'config' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CNFDEF
 *
 * Looks to match the characters the constitute the token CNFDEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCNFDEF(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = CNFDEF;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:93:9: ( 'config' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:93:11: 'config'
    {
        MATCHS(lit_9); 
        if  (HASEXCEPTION())
        {
            goto ruleCNFDEFEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCNFDEFEx; /* Prevent compiler warnings */
    ruleCNFDEFEx: ;

}
// $ANTLR end CNFDEF

//   Comes from: 95:9: ( INTEGER '.' INTEGER )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FLOAT
 *
 * Looks to match the characters the constitute the token FLOAT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFLOAT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = FLOAT;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:95:9: ( INTEGER '.' INTEGER )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:95:11: INTEGER '.' INTEGER
    {
        /* 95:11: INTEGER '.' INTEGER */
        mINTEGER(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleFLOATEx;
        }

        MATCHC('.'); 
        if  (HASEXCEPTION())
        {
            goto ruleFLOATEx;
        }

        /* 95:11: INTEGER '.' INTEGER */
        mINTEGER(ctx ); 
        if  (HASEXCEPTION())
        {
            goto ruleFLOATEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleFLOATEx; /* Prevent compiler warnings */
    ruleFLOATEx: ;

}
// $ANTLR end FLOAT

//   Comes from: 96:9: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NAME
 *
 * Looks to match the characters the constitute the token NAME
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNAME(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = NAME;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:96:9: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:96:11: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleNAMEEx;
        }


        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:96:38: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt7=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA7_0 = LA(1);
                if ( (((LA7_0 >= '0') && (LA7_0 <= '9')) || ((LA7_0 >= 'A') && (LA7_0 <= 'Z')) || LA7_0 == '_' || ((LA7_0 >= 'a') && (LA7_0 <= 'z'))) ) 
                {
                    alt7=1;
                }

            }
            switch (alt7) 
            {
        	case 1:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleNAMEEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop7;	/* break out of the loop */
        	    break;
            }
        }
        loop7: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleNAMEEx; /* Prevent compiler warnings */
    ruleNAMEEx: ;

}
// $ANTLR end NAME

//   Comes from: 98:9: ( '/*' ( . )* '*/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MCMT
 *
 * Looks to match the characters the constitute the token MCMT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMCMT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = MCMT;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:98:9: ( '/*' ( . )* '*/' )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:98:11: '/*' ( . )* '*/'
    {
        MATCHS(lit_10); 
        if  (HASEXCEPTION())
        {
            goto ruleMCMTEx;
        }



        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:98:16: ( . )*

        for (;;)
        {
            int alt8=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA8_0 = LA(1);
                if ( (LA8_0 == '*') ) 
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA8_1 = LA(2);
                        if ( (LA8_1 == '/') ) 
                        {
                            alt8=2;
                        }
                        else if ( (((LA8_1 >= 0x0000) && (LA8_1 <= '.')) || ((LA8_1 >= '0') && (LA8_1 <= 0xFFFF))) ) 
                        {
                            alt8=1;
                        }

                    }
                }
                else if ( (((LA8_0 >= 0x0000) && (LA8_0 <= ')')) || ((LA8_0 >= '+') && (LA8_0 <= 0xFFFF))) ) 
                {
                    alt8=1;
                }

            }
            switch (alt8) 
            {
        	case 1:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:98:16: .
        	    {
        	        MATCHANY(); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleMCMTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop8;	/* break out of the loop */
        	    break;
            }
        }
        loop8: ; /* Jump out to here if this rule does not match */

        MATCHS(lit_11); 
        if  (HASEXCEPTION())
        {
            goto ruleMCMTEx;
        }


        {
             LEXSTATE->channel=HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleMCMTEx; /* Prevent compiler warnings */
    ruleMCMTEx: ;

}
// $ANTLR end MCMT

//   Comes from: 99:9: ( '//' (~ ( '\\n' | '\\r' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SCMT
 *
 * Looks to match the characters the constitute the token SCMT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSCMT(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = SCMT;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:99:9: ( '//' (~ ( '\\n' | '\\r' ) )* )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:99:11: '//' (~ ( '\\n' | '\\r' ) )*
    {
        MATCHS(lit_12); 
        if  (HASEXCEPTION())
        {
            goto ruleSCMTEx;
        }



        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:99:16: (~ ( '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt9=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA9_0 = LA(1);
                if ( (((LA9_0 >= 0x0000) && (LA9_0 <= '\t')) || ((LA9_0 >= 0x000B) && (LA9_0 <= '\f')) || ((LA9_0 >= 0x000E) && (LA9_0 <= 0xFFFF))) ) 
                {
                    alt9=1;
                }

            }
            switch (alt9) 
            {
        	case 1:
        	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:99:17: ~ ( '\\n' | '\\r' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleSCMTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop9;	/* break out of the loop */
        	    break;
            }
        }
        loop9: ; /* Jump out to here if this rule does not match */

        {
             LEXSTATE->channel=HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSCMTEx; /* Prevent compiler warnings */
    ruleSCMTEx: ;

}
// $ANTLR end SCMT

//   Comes from: 100:9: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pislLexer ctx)
{
	ANTLR3_UINT32	_type;

   
    _type	    = WS;
       
    
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:100:9: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:100:11: ( ' ' | '\\t' | '\\r' | '\\n' )+
    {
        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:100:11: ( ' ' | '\\t' | '\\r' | '\\n' )+
        {
            int cnt10=0;

            for (;;)
            {
                int alt10=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA10_0 = LA(1);
        	    if ( (((LA10_0 >= '\t') && (LA10_0 <= '\n')) || LA10_0 == '\r' || LA10_0 == ' ') ) 
        	    {
        	        alt10=1;
        	    }

        	}
        	switch (alt10) 
        	{
        	    case 1:
        	        // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt10 >= 1 )
        		{
        		    goto loop10;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt10++;
            }
            loop10: ;	/* Jump to here if this rule does not match */
        }
        {
             LEXSTATE->channel = HIDDEN; 
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pislLexer ctx)
{
    {
        //  C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:8: ( T__31 | STRING | DOT | COLON | COMMA | LPAREN | RPAREN | INTEGER | BTRUE | BFALSE | ASSIGN | ADD | SUB | MUL | DIV | STARTDEF | ENDDEF | COLDEF | MATDEF | CNFDEF | FLOAT | NAME | MCMT | SCMT | WS )
        
        ANTLR3_UINT32 alt11;

        alt11=25;

        alt11 = cdfa11.predict(ctx, RECOGNIZER, ISTREAM, &cdfa11);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt11) 
        {
    	case 1:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:10: T__31
    	    {
    	        /* 1:10: T__31 */
    	        mT__31(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:16: STRING
    	    {
    	        /* 1:16: STRING */
    	        mSTRING(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:23: DOT
    	    {
    	        /* 1:23: DOT */
    	        mDOT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:27: COLON
    	    {
    	        /* 1:27: COLON */
    	        mCOLON(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:33: COMMA
    	    {
    	        /* 1:33: COMMA */
    	        mCOMMA(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:39: LPAREN
    	    {
    	        /* 1:39: LPAREN */
    	        mLPAREN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:46: RPAREN
    	    {
    	        /* 1:46: RPAREN */
    	        mRPAREN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:53: INTEGER
    	    {
    	        /* 1:53: INTEGER */
    	        mINTEGER(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:61: BTRUE
    	    {
    	        /* 1:61: BTRUE */
    	        mBTRUE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:67: BFALSE
    	    {
    	        /* 1:67: BFALSE */
    	        mBFALSE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:74: ASSIGN
    	    {
    	        /* 1:74: ASSIGN */
    	        mASSIGN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:81: ADD
    	    {
    	        /* 1:81: ADD */
    	        mADD(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:85: SUB
    	    {
    	        /* 1:85: SUB */
    	        mSUB(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:89: MUL
    	    {
    	        /* 1:89: MUL */
    	        mMUL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:93: DIV
    	    {
    	        /* 1:93: DIV */
    	        mDIV(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:97: STARTDEF
    	    {
    	        /* 1:97: STARTDEF */
    	        mSTARTDEF(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:106: ENDDEF
    	    {
    	        /* 1:106: ENDDEF */
    	        mENDDEF(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:113: COLDEF
    	    {
    	        /* 1:113: COLDEF */
    	        mCOLDEF(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:120: MATDEF
    	    {
    	        /* 1:120: MATDEF */
    	        mMATDEF(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:127: CNFDEF
    	    {
    	        /* 1:127: CNFDEF */
    	        mCNFDEF(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:134: FLOAT
    	    {
    	        /* 1:134: FLOAT */
    	        mFLOAT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:140: NAME
    	    {
    	        /* 1:140: NAME */
    	        mNAME(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:145: MCMT
    	    {
    	        /* 1:145: MCMT */
    	        mMCMT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 24:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:150: SCMT
    	    {
    	        /* 1:150: SCMT */
    	        mSCMT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 25:
    	    // C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g:1:155: WS
    	    {
    	        /* 1:155: WS */
    	        mWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
