/** \file
 *  This C header file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : C:\\gdev\\itubras\\tools\\isl\\grammar\\isl.g
 *     -                            On : 2008-10-24 09:13:05
 *     -                for the parser : islParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser islParser has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pislParser, which is returned from a call to islParserNew().
 *
 * The methods in pislParser are  as follows:
 *
 *  - islParser_script_return      pislParser->script(pislParser)
 *  - islParser_statements_return      pislParser->statements(pislParser)
 *  - islParser_object_return      pislParser->object(pislParser)
 *  - islParser_block_return      pislParser->block(pislParser)
 *  - islParser_objectType_return      pislParser->objectType(pislParser)
 *  - islParser_objectMaterial_return      pislParser->objectMaterial(pislParser)
 *  - islParser_objectConfig_return      pislParser->objectConfig(pislParser)
 *  - islParser_objectLayer_return      pislParser->objectLayer(pislParser)
 *  - islParser_objectMatrix_return      pislParser->objectMatrix(pislParser)
 *  - islParser_assignment_return      pislParser->assignment(pislParser)
 *  - islParser_object_or_expr_return      pislParser->object_or_expr(pislParser)
 *  - islParser_expr_return      pislParser->expr(pislParser)
 *  - islParser_mexpr_return      pislParser->mexpr(pislParser)
 *  - islParser_atom_return      pislParser->atom(pislParser)
 *  - islParser_tuple_or_expr_return      pislParser->tuple_or_expr(pislParser)
 *  - islParser_id_return      pislParser->id(pislParser)
 *  - islParser_idinherit_return      pislParser->idinherit(pislParser)
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
#ifndef	_islParser_H
#define _islParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct islParser_Ctx_struct islParser, * pislParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */
typedef struct islParser_script_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_script_return;

typedef struct islParser_statements_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_statements_return;

typedef struct islParser_object_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_object_return;

typedef struct islParser_block_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_block_return;

typedef struct islParser_objectType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_objectType_return;

typedef struct islParser_objectMaterial_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_objectMaterial_return;

typedef struct islParser_objectConfig_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_objectConfig_return;

typedef struct islParser_objectLayer_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_objectLayer_return;

typedef struct islParser_objectMatrix_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_objectMatrix_return;

typedef struct islParser_assignment_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_assignment_return;

typedef struct islParser_object_or_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_object_or_expr_return;

typedef struct islParser_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_expr_return;

typedef struct islParser_mexpr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_mexpr_return;

typedef struct islParser_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_atom_return;

typedef struct islParser_tuple_or_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_tuple_or_expr_return;

typedef struct islParser_id_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_id_return;

typedef struct islParser_idinherit_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    islParser_idinherit_return;




/** Context tracking structure for islParser
 */
struct islParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;


     islParser_script_return (*script)	(struct islParser_Ctx_struct * ctx);
     islParser_statements_return (*statements)	(struct islParser_Ctx_struct * ctx);
     islParser_object_return (*object)	(struct islParser_Ctx_struct * ctx);
     islParser_block_return (*block)	(struct islParser_Ctx_struct * ctx);
     islParser_objectType_return (*objectType)	(struct islParser_Ctx_struct * ctx);
     islParser_objectMaterial_return (*objectMaterial)	(struct islParser_Ctx_struct * ctx);
     islParser_objectConfig_return (*objectConfig)	(struct islParser_Ctx_struct * ctx);
     islParser_objectLayer_return (*objectLayer)	(struct islParser_Ctx_struct * ctx);
     islParser_objectMatrix_return (*objectMatrix)	(struct islParser_Ctx_struct * ctx);
     islParser_assignment_return (*assignment)	(struct islParser_Ctx_struct * ctx);
     islParser_object_or_expr_return (*object_or_expr)	(struct islParser_Ctx_struct * ctx);
     islParser_expr_return (*expr)	(struct islParser_Ctx_struct * ctx);
     islParser_mexpr_return (*mexpr)	(struct islParser_Ctx_struct * ctx);
     islParser_atom_return (*atom)	(struct islParser_Ctx_struct * ctx);
     islParser_tuple_or_expr_return (*tuple_or_expr)	(struct islParser_Ctx_struct * ctx);
     islParser_id_return (*id)	(struct islParser_Ctx_struct * ctx);
     islParser_idinherit_return (*idinherit)	(struct islParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred1_isl)	(struct islParser_Ctx_struct * ctx);
    // Delegated rules
    const char * (*getGrammarFileName)();
    void	    (*free)   (struct islParser_Ctx_struct * ctx);
    /* @headerFile.members() */
    pANTLR3_BASE_TREE_ADAPTOR	adaptor;
    pANTLR3_VECTOR_FACTORY		vectors;
    /* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pislParser islParserNew         (pANTLR3_COMMON_TOKEN_STREAM instream);
ANTLR3_API pislParser islParserNewSSD      (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the parser will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define INTEGER      19
#define MATDEF      9
#define LAYDEF      11
#define LINE_COMMENT      35
#define INHERIT      6
#define SDEF      7
#define BOOLLITERAL      22
#define SUB      15
#define FLOAT      18
#define EOF      -1
#define HexDigit      32
#define MUL      16
#define LPAREN      23
#define COLON      28
#define RPAREN      25
#define TUPLE      5
#define NAME      26
#define WS      33
#define CNFDEF      10
#define COMMA      24
#define HEX      20
#define UnicodeEscape      30
#define LINE_COMMAND      36
#define ASSIGN      4
#define EDEF      8
#define DIV      17
#define COMMENT      34
#define DOT      27
#define OctalEscape      31
#define EscapeSequence      29
#define STRING      21
#define MTXDEF      12
#define SCOLON      13
#define ADD      14
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for islParser
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
