/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g
 *     -                            On : 2008-10-12 11:00:48
 *     -                for the parser : islParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "islParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pislParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pislParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pislParser_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   islParserTokenNames[28+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "OBJECT",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "ADD",
        (pANTLR3_UINT8) "SUB",
        (pANTLR3_UINT8) "MUL",
        (pANTLR3_UINT8) "DIV",
        (pANTLR3_UINT8) "FLOAT",
        (pANTLR3_UINT8) "INTEGER",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "LPAREN",
        (pANTLR3_UINT8) "RPAREN",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "NAME",
        (pANTLR3_UINT8) "DOT",
        (pANTLR3_UINT8) "COLON",
        (pANTLR3_UINT8) "MCMT",
        (pANTLR3_UINT8) "SCMT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'",
        (pANTLR3_UINT8) "'color'",
        (pANTLR3_UINT8) "'material'",
        (pANTLR3_UINT8) "'config'",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'+'",
        (pANTLR3_UINT8) "'-'",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "'/'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static islParser_script_return	script    (pislParser ctx);
static islParser_statements_return	statements    (pislParser ctx);
static islParser_classdef_return	classdef    (pislParser ctx);
static islParser_classType_return	classType    (pislParser ctx);
static islParser_classColor_return	classColor    (pislParser ctx);
static islParser_classMaterial_return	classMaterial    (pislParser ctx);
static islParser_classConfig_return	classConfig    (pislParser ctx);
static islParser_cstatements_return	cstatements    (pislParser ctx);
static islParser_assignment_return	assignment    (pislParser ctx);
static islParser_expr_or_def_return	expr_or_def    (pislParser ctx);
static islParser_addexpr_return	addexpr    (pislParser ctx);
static islParser_mulexpr_return	mulexpr    (pislParser ctx);
static islParser_atom_return	atom    (pislParser ctx);
static islParser_list_or_expr_return	list_or_expr    (pislParser ctx);
static islParser_id_return	id    (pislParser ctx);
static islParser_idinherit_return	idinherit    (pislParser ctx);
static void	islParserFree(pislParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new islParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pislParser
islParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return islParserNewSSD(instream, NULL);
}

/** \brief Create a new islParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pislParser
islParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pislParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pislParser) ANTLR3_CALLOC(1, sizeof(islParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in islParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our islParser interface
     */
    ctx->script	= script;
    ctx->statements	= statements;
    ctx->classdef	= classdef;
    ctx->classType	= classType;
    ctx->classColor	= classColor;
    ctx->classMaterial	= classMaterial;
    ctx->classConfig	= classConfig;
    ctx->cstatements	= cstatements;
    ctx->assignment	= assignment;
    ctx->expr_or_def	= expr_or_def;
    ctx->addexpr	= addexpr;
    ctx->mulexpr	= mulexpr;
    ctx->atom	= atom;
    ctx->list_or_expr	= list_or_expr;
    ctx->id	= id;
    ctx->idinherit	= idinherit;
    ctx->free			= islParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(64);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = islParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 islParserFree(pislParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return islParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_statements_in_script86  */
static	ANTLR3_BITWORD FOLLOW_statements_in_script86_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007010002) };
static  ANTLR3_BITSET_LIST FOLLOW_statements_in_script86	= { FOLLOW_statements_in_script86_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classdef_in_statements107  */
static	ANTLR3_BITWORD FOLLOW_classdef_in_statements107_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classdef_in_statements107	= { FOLLOW_classdef_in_statements107_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_statements115  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_statements115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_statements115	= { FOLLOW_assignment_in_statements115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classType_in_classdef131  */
static	ANTLR3_BITWORD FOLLOW_classType_in_classdef131_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_classType_in_classdef131	= { FOLLOW_classType_in_classdef131_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_classdef133  */
static	ANTLR3_BITWORD FOLLOW_22_in_classdef133_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007810000) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_classdef133	= { FOLLOW_22_in_classdef133_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_cstatements_in_classdef135  */
static	ANTLR3_BITWORD FOLLOW_cstatements_in_classdef135_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007810000) };
static  ANTLR3_BITSET_LIST FOLLOW_cstatements_in_classdef135	= { FOLLOW_cstatements_in_classdef135_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_classdef138  */
static	ANTLR3_BITWORD FOLLOW_23_in_classdef138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_classdef138	= { FOLLOW_23_in_classdef138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classColor_in_classType154  */
static	ANTLR3_BITWORD FOLLOW_classColor_in_classType154_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classColor_in_classType154	= { FOLLOW_classColor_in_classType154_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classMaterial_in_classType164  */
static	ANTLR3_BITWORD FOLLOW_classMaterial_in_classType164_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classMaterial_in_classType164	= { FOLLOW_classMaterial_in_classType164_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classConfig_in_classType174  */
static	ANTLR3_BITWORD FOLLOW_classConfig_in_classType174_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classConfig_in_classType174	= { FOLLOW_classConfig_in_classType174_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_classColor191  */
static	ANTLR3_BITWORD FOLLOW_24_in_classColor191_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_classColor191	= { FOLLOW_24_in_classColor191_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idinherit_in_classColor194  */
static	ANTLR3_BITWORD FOLLOW_idinherit_in_classColor194_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idinherit_in_classColor194	= { FOLLOW_idinherit_in_classColor194_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_25_in_classMaterial202  */
static	ANTLR3_BITWORD FOLLOW_25_in_classMaterial202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_25_in_classMaterial202	= { FOLLOW_25_in_classMaterial202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idinherit_in_classMaterial205  */
static	ANTLR3_BITWORD FOLLOW_idinherit_in_classMaterial205_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idinherit_in_classMaterial205	= { FOLLOW_idinherit_in_classMaterial205_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_classConfig213  */
static	ANTLR3_BITWORD FOLLOW_26_in_classConfig213_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010002) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_classConfig213	= { FOLLOW_26_in_classConfig213_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idinherit_in_classConfig216  */
static	ANTLR3_BITWORD FOLLOW_idinherit_in_classConfig216_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idinherit_in_classConfig216	= { FOLLOW_idinherit_in_classConfig216_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classdef_in_cstatements233  */
static	ANTLR3_BITWORD FOLLOW_classdef_in_cstatements233_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classdef_in_cstatements233	= { FOLLOW_classdef_in_cstatements233_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_cstatements241  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_cstatements241_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_cstatements241	= { FOLLOW_assignment_in_cstatements241_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_id_in_assignment253  */
static	ANTLR3_BITWORD FOLLOW_id_in_assignment253_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_id_in_assignment253	= { FOLLOW_id_in_assignment253_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_assignment255  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_assignment255_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007013C00) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_assignment255	= { FOLLOW_ASSIGN_in_assignment255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_or_def_in_assignment258  */
static	ANTLR3_BITWORD FOLLOW_expr_or_def_in_assignment258_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_or_def_in_assignment258	= { FOLLOW_expr_or_def_in_assignment258_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_27_in_assignment260  */
static	ANTLR3_BITWORD FOLLOW_27_in_assignment260_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_27_in_assignment260	= { FOLLOW_27_in_assignment260_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addexpr_in_expr_or_def283  */
static	ANTLR3_BITWORD FOLLOW_addexpr_in_expr_or_def283_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_addexpr_in_expr_or_def283	= { FOLLOW_addexpr_in_expr_or_def283_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classdef_in_expr_or_def287  */
static	ANTLR3_BITWORD FOLLOW_classdef_in_expr_or_def287_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classdef_in_expr_or_def287	= { FOLLOW_classdef_in_expr_or_def287_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_mulexpr_in_addexpr307  */
static	ANTLR3_BITWORD FOLLOW_mulexpr_in_addexpr307_bits[]	= { ANTLR3_UINT64_LIT(0x0000000030000002) };
static  ANTLR3_BITSET_LIST FOLLOW_mulexpr_in_addexpr307	= { FOLLOW_mulexpr_in_addexpr307_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_28_in_addexpr311  */
static	ANTLR3_BITWORD FOLLOW_28_in_addexpr311_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007013C00) };
static  ANTLR3_BITSET_LIST FOLLOW_28_in_addexpr311	= { FOLLOW_28_in_addexpr311_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_mulexpr_in_addexpr314  */
static	ANTLR3_BITWORD FOLLOW_mulexpr_in_addexpr314_bits[]	= { ANTLR3_UINT64_LIT(0x0000000030000002) };
static  ANTLR3_BITSET_LIST FOLLOW_mulexpr_in_addexpr314	= { FOLLOW_mulexpr_in_addexpr314_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_29_in_addexpr318  */
static	ANTLR3_BITWORD FOLLOW_29_in_addexpr318_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007013C00) };
static  ANTLR3_BITSET_LIST FOLLOW_29_in_addexpr318	= { FOLLOW_29_in_addexpr318_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_mulexpr_in_addexpr321  */
static	ANTLR3_BITWORD FOLLOW_mulexpr_in_addexpr321_bits[]	= { ANTLR3_UINT64_LIT(0x0000000030000002) };
static  ANTLR3_BITSET_LIST FOLLOW_mulexpr_in_addexpr321	= { FOLLOW_mulexpr_in_addexpr321_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_mulexpr331  */
static	ANTLR3_BITWORD FOLLOW_atom_in_mulexpr331_bits[]	= { ANTLR3_UINT64_LIT(0x00000000C0000002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_mulexpr331	= { FOLLOW_atom_in_mulexpr331_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_30_in_mulexpr334  */
static	ANTLR3_BITWORD FOLLOW_30_in_mulexpr334_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007013C00) };
static  ANTLR3_BITSET_LIST FOLLOW_30_in_mulexpr334	= { FOLLOW_30_in_mulexpr334_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_mulexpr337  */
static	ANTLR3_BITWORD FOLLOW_atom_in_mulexpr337_bits[]	= { ANTLR3_UINT64_LIT(0x00000000C0000002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_mulexpr337	= { FOLLOW_atom_in_mulexpr337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_31_in_mulexpr341  */
static	ANTLR3_BITWORD FOLLOW_31_in_mulexpr341_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007013C00) };
static  ANTLR3_BITSET_LIST FOLLOW_31_in_mulexpr341	= { FOLLOW_31_in_mulexpr341_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_mulexpr344  */
static	ANTLR3_BITWORD FOLLOW_atom_in_mulexpr344_bits[]	= { ANTLR3_UINT64_LIT(0x00000000C0000002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_mulexpr344	= { FOLLOW_atom_in_mulexpr344_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_id_in_atom369  */
static	ANTLR3_BITWORD FOLLOW_id_in_atom369_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_id_in_atom369	= { FOLLOW_id_in_atom369_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_atom377  */
static	ANTLR3_BITWORD FOLLOW_FLOAT_in_atom377_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_atom377	= { FOLLOW_FLOAT_in_atom377_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INTEGER_in_atom385  */
static	ANTLR3_BITWORD FOLLOW_INTEGER_in_atom385_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INTEGER_in_atom385	= { FOLLOW_INTEGER_in_atom385_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_atom393  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_atom393_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_atom393	= { FOLLOW_STRING_in_atom393_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAREN_in_atom401  */
static	ANTLR3_BITWORD FOLLOW_LPAREN_in_atom401_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007017C00) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAREN_in_atom401	= { FOLLOW_LPAREN_in_atom401_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_list_or_expr_in_atom403  */
static	ANTLR3_BITWORD FOLLOW_list_or_expr_in_atom403_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_list_or_expr_in_atom403	= { FOLLOW_list_or_expr_in_atom403_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_atom406  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_atom406_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_atom406	= { FOLLOW_RPAREN_in_atom406_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addexpr_in_list_or_expr430  */
static	ANTLR3_BITWORD FOLLOW_addexpr_in_list_or_expr430_bits[]	= { ANTLR3_UINT64_LIT(0x000000000701BC02) };
static  ANTLR3_BITSET_LIST FOLLOW_addexpr_in_list_or_expr430	= { FOLLOW_addexpr_in_list_or_expr430_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COMMA_in_list_or_expr433  */
static	ANTLR3_BITWORD FOLLOW_COMMA_in_list_or_expr433_bits[]	= { ANTLR3_UINT64_LIT(0x0000000007013C00) };
static  ANTLR3_BITSET_LIST FOLLOW_COMMA_in_list_or_expr433	= { FOLLOW_COMMA_in_list_or_expr433_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addexpr_in_list_or_expr436  */
static	ANTLR3_BITWORD FOLLOW_addexpr_in_list_or_expr436_bits[]	= { ANTLR3_UINT64_LIT(0x000000000701BC02) };
static  ANTLR3_BITSET_LIST FOLLOW_addexpr_in_list_or_expr436	= { FOLLOW_addexpr_in_list_or_expr436_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_id460  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_id460_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_id460	= { FOLLOW_NAME_in_id460_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DOT_in_id463  */
static	ANTLR3_BITWORD FOLLOW_DOT_in_id463_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_DOT_in_id463	= { FOLLOW_DOT_in_id463_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_id465  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_id465_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020002) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_id465	= { FOLLOW_NAME_in_id465_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_idinherit474  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_idinherit474_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_idinherit474	= { FOLLOW_NAME_in_idinherit474_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_idinherit479  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_idinherit479_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_idinherit479	= { FOLLOW_NAME_in_idinherit479_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COLON_in_idinherit481  */
static	ANTLR3_BITWORD FOLLOW_COLON_in_idinherit481_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_COLON_in_idinherit481	= { FOLLOW_COLON_in_idinherit481_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_idinherit484  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_idinherit484_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_idinherit484	= { FOLLOW_NAME_in_idinherit484_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start script
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:16:1: script : ( statements )+ ;
 */
static islParser_script_return
script(pislParser ctx)
{   
    islParser_script_return retval;

    pANTLR3_BASE_TREE root_0;

    islParser_statements_return statements1;
    #undef	RETURN_TYPE_statements1
    #define	RETURN_TYPE_statements1 islParser_statements_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    statements1.tree = NULL;

    retval.start = LT(1);

    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:16:8: ( ( statements )+ )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:16:10: ( statements )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:16:10: ( statements )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA1_0 = LA(1);
            	    if ( (LA1_0 == NAME || ((LA1_0 >= 24) && (LA1_0 <= 26))) ) 
            	    {
            	        alt1=1;
            	    }

            	}
            	switch (alt1) 
            	{
            	    case 1:
            	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:16:10: statements
            	        {
            	            FOLLOWPUSH(FOLLOW_statements_in_script86);
            	            statements1=statements(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulescriptEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, statements1.tree);

            	        }
            	        break;

            	    default:
            	    
            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulescriptEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulescriptEx; /* Prevent compiler warnings */
    rulescriptEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end script */

/** 
 * $ANTLR start statements
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:19:1: statements : ( classdef | assignment );
 */
static islParser_statements_return
statements(pislParser ctx)
{   
    islParser_statements_return retval;

    pANTLR3_BASE_TREE root_0;

    islParser_classdef_return classdef2;
    #undef	RETURN_TYPE_classdef2
    #define	RETURN_TYPE_classdef2 islParser_classdef_return

    islParser_assignment_return assignment3;
    #undef	RETURN_TYPE_assignment3
    #define	RETURN_TYPE_assignment3 islParser_assignment_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    classdef2.tree = NULL;

    assignment3.tree = NULL;

    retval.start = LT(1);

    retval.tree  = NULL;
    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:19:12: ( classdef | assignment )
            
            ANTLR3_UINT32 alt2;

            alt2=2;


            {
                int LA2_0 = LA(1);
                if ( (((LA2_0 >= 24) && (LA2_0 <= 26))) ) 
                {
                    alt2=1;
                }
                else if ( (LA2_0 == NAME) ) 
                {
                    alt2=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 2;
                    EXCEPTION->state        = 0;


                    goto rulestatementsEx;
                }
            }
            switch (alt2) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:20:7: classdef
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_classdef_in_statements107);
        	        classdef2=classdef(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementsEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, classdef2.tree);

        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:21:7: assignment
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_assignment_in_statements115);
        	        assignment3=assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementsEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, assignment3.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulestatementsEx; /* Prevent compiler warnings */
    rulestatementsEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end statements */

/** 
 * $ANTLR start classdef
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:24:1: classdef : classType '{' ( cstatements )* '}' ;
 */
static islParser_classdef_return
classdef(pislParser ctx)
{   
    islParser_classdef_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal5;
    pANTLR3_COMMON_TOKEN    char_literal7;
    islParser_classType_return classType4;
    #undef	RETURN_TYPE_classType4
    #define	RETURN_TYPE_classType4 islParser_classType_return

    islParser_cstatements_return cstatements6;
    #undef	RETURN_TYPE_cstatements6
    #define	RETURN_TYPE_cstatements6 islParser_cstatements_return

    pANTLR3_BASE_TREE char_literal5_tree;
    pANTLR3_BASE_TREE char_literal7_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    char_literal5       = NULL;
    char_literal7       = NULL;
    classType4.tree = NULL;

    cstatements6.tree = NULL;

    retval.start = LT(1);

    char_literal5_tree   = NULL;
    char_literal7_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:24:9: ( classType '{' ( cstatements )* '}' )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:25:5: classType '{' ( cstatements )* '}'
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_classType_in_classdef131);
            classType4=classType(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleclassdefEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, classType4.tree);
            char_literal5 = (pANTLR3_COMMON_TOKEN) MATCHT(22, &FOLLOW_22_in_classdef133); 
            if  (HASEXCEPTION())
            {
                goto ruleclassdefEx;
            }

            char_literal5_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal5));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal5_tree);


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:25:19: ( cstatements )*

            for (;;)
            {
                int alt3=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA3_0 = LA(1);
                    if ( (LA3_0 == NAME || ((LA3_0 >= 24) && (LA3_0 <= 26))) ) 
                    {
                        alt3=1;
                    }

                }
                switch (alt3) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:25:19: cstatements
            	    {
            	        FOLLOWPUSH(FOLLOW_cstatements_in_classdef135);
            	        cstatements6=cstatements(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassdefEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, cstatements6.tree);

            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */

            char_literal7 = (pANTLR3_COMMON_TOKEN) MATCHT(23, &FOLLOW_23_in_classdef138); 
            if  (HASEXCEPTION())
            {
                goto ruleclassdefEx;
            }

            char_literal7_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal7));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal7_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassdefEx; /* Prevent compiler warnings */
    ruleclassdefEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end classdef */

/** 
 * $ANTLR start classType
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:27:1: classType : ( classColor | classMaterial | classConfig );
 */
static islParser_classType_return
classType(pislParser ctx)
{   
    islParser_classType_return retval;

    pANTLR3_BASE_TREE root_0;

    islParser_classColor_return classColor8;
    #undef	RETURN_TYPE_classColor8
    #define	RETURN_TYPE_classColor8 islParser_classColor_return

    islParser_classMaterial_return classMaterial9;
    #undef	RETURN_TYPE_classMaterial9
    #define	RETURN_TYPE_classMaterial9 islParser_classMaterial_return

    islParser_classConfig_return classConfig10;
    #undef	RETURN_TYPE_classConfig10
    #define	RETURN_TYPE_classConfig10 islParser_classConfig_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    classColor8.tree = NULL;

    classMaterial9.tree = NULL;

    classConfig10.tree = NULL;

    retval.start = LT(1);

    retval.tree  = NULL;
    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:27:11: ( classColor | classMaterial | classConfig )
            
            ANTLR3_UINT32 alt4;

            alt4=3;

            switch ( LA(1) ) 
            {
            case 24:
            	{
            		alt4=1;
            	}
                break;
            case 25:
            	{
            		alt4=2;
            	}
                break;
            case 26:
            	{
            		alt4=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 4;
                EXCEPTION->state        = 0;


                goto ruleclassTypeEx;
            }

            switch (alt4) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:28:9: classColor
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_classColor_in_classType154);
        	        classColor8=classColor(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleclassTypeEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, classColor8.tree);

        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:29:9: classMaterial
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_classMaterial_in_classType164);
        	        classMaterial9=classMaterial(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleclassTypeEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, classMaterial9.tree);

        	    }
        	    break;
        	case 3:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:30:9: classConfig
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_classConfig_in_classType174);
        	        classConfig10=classConfig(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleclassTypeEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, classConfig10.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassTypeEx; /* Prevent compiler warnings */
    ruleclassTypeEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end classType */

/** 
 * $ANTLR start classColor
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:33:1: classColor : 'color' ( idinherit )? ;
 */
static islParser_classColor_return
classColor(pislParser ctx)
{   
    islParser_classColor_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal11;
    islParser_idinherit_return idinherit12;
    #undef	RETURN_TYPE_idinherit12
    #define	RETURN_TYPE_idinherit12 islParser_idinherit_return

    pANTLR3_BASE_TREE string_literal11_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    string_literal11       = NULL;
    idinherit12.tree = NULL;

    retval.start = LT(1);

    string_literal11_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:33:12: ( 'color' ( idinherit )? )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:33:14: 'color' ( idinherit )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal11 = (pANTLR3_COMMON_TOKEN) MATCHT(24, &FOLLOW_24_in_classColor191); 
            if  (HASEXCEPTION())
            {
                goto ruleclassColorEx;
            }

            string_literal11_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal11));
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, string_literal11_tree, root_0));


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:33:23: ( idinherit )?
            {
                int alt5=2;
                {
                    int LA5_0 = LA(1);
                    if ( (LA5_0 == NAME) ) 
                    {
                        alt5=1;
                    }
                }
                switch (alt5) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:33:23: idinherit
            	    {
            	        FOLLOWPUSH(FOLLOW_idinherit_in_classColor194);
            	        idinherit12=idinherit(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassColorEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, idinherit12.tree);

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassColorEx; /* Prevent compiler warnings */
    ruleclassColorEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end classColor */

/** 
 * $ANTLR start classMaterial
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:34:1: classMaterial : 'material' ( idinherit )? ;
 */
static islParser_classMaterial_return
classMaterial(pislParser ctx)
{   
    islParser_classMaterial_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal13;
    islParser_idinherit_return idinherit14;
    #undef	RETURN_TYPE_idinherit14
    #define	RETURN_TYPE_idinherit14 islParser_idinherit_return

    pANTLR3_BASE_TREE string_literal13_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    string_literal13       = NULL;
    idinherit14.tree = NULL;

    retval.start = LT(1);

    string_literal13_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:34:15: ( 'material' ( idinherit )? )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:34:17: 'material' ( idinherit )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal13 = (pANTLR3_COMMON_TOKEN) MATCHT(25, &FOLLOW_25_in_classMaterial202); 
            if  (HASEXCEPTION())
            {
                goto ruleclassMaterialEx;
            }

            string_literal13_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal13));
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, string_literal13_tree, root_0));


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:34:29: ( idinherit )?
            {
                int alt6=2;
                {
                    int LA6_0 = LA(1);
                    if ( (LA6_0 == NAME) ) 
                    {
                        alt6=1;
                    }
                }
                switch (alt6) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:34:29: idinherit
            	    {
            	        FOLLOWPUSH(FOLLOW_idinherit_in_classMaterial205);
            	        idinherit14=idinherit(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassMaterialEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, idinherit14.tree);

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassMaterialEx; /* Prevent compiler warnings */
    ruleclassMaterialEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end classMaterial */

/** 
 * $ANTLR start classConfig
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:35:1: classConfig : 'config' ( idinherit )? ;
 */
static islParser_classConfig_return
classConfig(pislParser ctx)
{   
    islParser_classConfig_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    string_literal15;
    islParser_idinherit_return idinherit16;
    #undef	RETURN_TYPE_idinherit16
    #define	RETURN_TYPE_idinherit16 islParser_idinherit_return

    pANTLR3_BASE_TREE string_literal15_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    string_literal15       = NULL;
    idinherit16.tree = NULL;

    retval.start = LT(1);

    string_literal15_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:35:13: ( 'config' ( idinherit )? )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:35:15: 'config' ( idinherit )?
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            string_literal15 = (pANTLR3_COMMON_TOKEN) MATCHT(26, &FOLLOW_26_in_classConfig213); 
            if  (HASEXCEPTION())
            {
                goto ruleclassConfigEx;
            }

            string_literal15_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, string_literal15));
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, string_literal15_tree, root_0));


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:35:25: ( idinherit )?
            {
                int alt7=2;
                {
                    int LA7_0 = LA(1);
                    if ( (LA7_0 == NAME) ) 
                    {
                        alt7=1;
                    }
                }
                switch (alt7) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:35:25: idinherit
            	    {
            	        FOLLOWPUSH(FOLLOW_idinherit_in_classConfig216);
            	        idinherit16=idinherit(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassConfigEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, idinherit16.tree);

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassConfigEx; /* Prevent compiler warnings */
    ruleclassConfigEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end classConfig */

/** 
 * $ANTLR start cstatements
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:37:1: cstatements : ( classdef | assignment );
 */
static islParser_cstatements_return
cstatements(pislParser ctx)
{   
    islParser_cstatements_return retval;

    pANTLR3_BASE_TREE root_0;

    islParser_classdef_return classdef17;
    #undef	RETURN_TYPE_classdef17
    #define	RETURN_TYPE_classdef17 islParser_classdef_return

    islParser_assignment_return assignment18;
    #undef	RETURN_TYPE_assignment18
    #define	RETURN_TYPE_assignment18 islParser_assignment_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    classdef17.tree = NULL;

    assignment18.tree = NULL;

    retval.start = LT(1);

    retval.tree  = NULL;
    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:37:12: ( classdef | assignment )
            
            ANTLR3_UINT32 alt8;

            alt8=2;


            {
                int LA8_0 = LA(1);
                if ( (((LA8_0 >= 24) && (LA8_0 <= 26))) ) 
                {
                    alt8=1;
                }
                else if ( (LA8_0 == NAME) ) 
                {
                    alt8=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 8;
                    EXCEPTION->state        = 0;


                    goto rulecstatementsEx;
                }
            }
            switch (alt8) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:38:9: classdef
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_classdef_in_cstatements233);
        	        classdef17=classdef(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecstatementsEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, classdef17.tree);

        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:39:7: assignment
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_assignment_in_cstatements241);
        	        assignment18=assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecstatementsEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, assignment18.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulecstatementsEx; /* Prevent compiler warnings */
    rulecstatementsEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end cstatements */

/** 
 * $ANTLR start assignment
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:41:1: assignment : id ASSIGN expr_or_def ';' ;
 */
static islParser_assignment_return
assignment(pislParser ctx)
{   
    islParser_assignment_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ASSIGN20;
    pANTLR3_COMMON_TOKEN    char_literal22;
    islParser_id_return id19;
    #undef	RETURN_TYPE_id19
    #define	RETURN_TYPE_id19 islParser_id_return

    islParser_expr_or_def_return expr_or_def21;
    #undef	RETURN_TYPE_expr_or_def21
    #define	RETURN_TYPE_expr_or_def21 islParser_expr_or_def_return

    pANTLR3_BASE_TREE ASSIGN20_tree;
    pANTLR3_BASE_TREE char_literal22_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    ASSIGN20       = NULL;
    char_literal22       = NULL;
    id19.tree = NULL;

    expr_or_def21.tree = NULL;

    retval.start = LT(1);

    ASSIGN20_tree   = NULL;
    char_literal22_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:41:12: ( id ASSIGN expr_or_def ';' )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:42:5: id ASSIGN expr_or_def ';'
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_id_in_assignment253);
            id19=id(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, id19.tree);
            ASSIGN20 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_assignment255); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            ASSIGN20_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ASSIGN20));
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, ASSIGN20_tree, root_0));

            FOLLOWPUSH(FOLLOW_expr_or_def_in_assignment258);
            expr_or_def21=expr_or_def(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, expr_or_def21.tree);
            char_literal22 = (pANTLR3_COMMON_TOKEN) MATCHT(27, &FOLLOW_27_in_assignment260); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleassignmentEx; /* Prevent compiler warnings */
    ruleassignmentEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end assignment */

/** 
 * $ANTLR start expr_or_def
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:45:1: expr_or_def : ( addexpr | classdef ) ;
 */
static islParser_expr_or_def_return
expr_or_def(pislParser ctx)
{   
    islParser_expr_or_def_return retval;

    pANTLR3_BASE_TREE root_0;

    islParser_addexpr_return addexpr23;
    #undef	RETURN_TYPE_addexpr23
    #define	RETURN_TYPE_addexpr23 islParser_addexpr_return

    islParser_classdef_return classdef24;
    #undef	RETURN_TYPE_classdef24
    #define	RETURN_TYPE_classdef24 islParser_classdef_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    addexpr23.tree = NULL;

    classdef24.tree = NULL;

    retval.start = LT(1);

    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:45:13: ( ( addexpr | classdef ) )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:46:5: ( addexpr | classdef )
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:46:5: ( addexpr | classdef )
            {
                int alt9=2;

                {
                    int LA9_0 = LA(1);
                    if ( (((LA9_0 >= FLOAT) && (LA9_0 <= LPAREN)) || LA9_0 == NAME) ) 
                    {
                        alt9=1;
                    }
                    else if ( (((LA9_0 >= 24) && (LA9_0 <= 26))) ) 
                    {
                        alt9=2;
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 9;
                        EXCEPTION->state        = 0;


                        goto ruleexpr_or_defEx;
                    }
                }
                switch (alt9) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:46:6: addexpr
            	    {
            	        FOLLOWPUSH(FOLLOW_addexpr_in_expr_or_def283);
            	        addexpr23=addexpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexpr_or_defEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, addexpr23.tree);

            	    }
            	    break;
            	case 2:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:46:16: classdef
            	    {
            	        FOLLOWPUSH(FOLLOW_classdef_in_expr_or_def287);
            	        classdef24=classdef(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexpr_or_defEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, classdef24.tree);

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleexpr_or_defEx; /* Prevent compiler warnings */
    ruleexpr_or_defEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end expr_or_def */

/** 
 * $ANTLR start addexpr
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:1: addexpr : ( mulexpr ) ( '+' mulexpr | '-' mulexpr )* ;
 */
static islParser_addexpr_return
addexpr(pislParser ctx)
{   
    islParser_addexpr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal26;
    pANTLR3_COMMON_TOKEN    char_literal28;
    islParser_mulexpr_return mulexpr25;
    #undef	RETURN_TYPE_mulexpr25
    #define	RETURN_TYPE_mulexpr25 islParser_mulexpr_return

    islParser_mulexpr_return mulexpr27;
    #undef	RETURN_TYPE_mulexpr27
    #define	RETURN_TYPE_mulexpr27 islParser_mulexpr_return

    islParser_mulexpr_return mulexpr29;
    #undef	RETURN_TYPE_mulexpr29
    #define	RETURN_TYPE_mulexpr29 islParser_mulexpr_return

    pANTLR3_BASE_TREE char_literal26_tree;
    pANTLR3_BASE_TREE char_literal28_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    char_literal26       = NULL;
    char_literal28       = NULL;
    mulexpr25.tree = NULL;

    mulexpr27.tree = NULL;

    mulexpr29.tree = NULL;

    retval.start = LT(1);

    char_literal26_tree   = NULL;
    char_literal28_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:9: ( ( mulexpr ) ( '+' mulexpr | '-' mulexpr )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:11: ( mulexpr ) ( '+' mulexpr | '-' mulexpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:11: ( mulexpr )
            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:12: mulexpr
            {
                FOLLOWPUSH(FOLLOW_mulexpr_in_addexpr307);
                mulexpr25=mulexpr(ctx);

                FOLLOWPOP();
                if  (HASEXCEPTION())
                {
                    goto ruleaddexprEx;
                }

                ADAPTOR->addChild(ADAPTOR, root_0, mulexpr25.tree);

            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:21: ( '+' mulexpr | '-' mulexpr )*

            for (;;)
            {
                int alt10=3;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA10_0 = LA(1);
                    if ( (LA10_0 == 28) ) 
                    {
                        alt10=1;
                    }
                    else if ( (LA10_0 == 29) ) 
                    {
                        alt10=2;
                    }

                }
                switch (alt10) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:22: '+' mulexpr
            	    {
            	        char_literal26 = (pANTLR3_COMMON_TOKEN) MATCHT(28, &FOLLOW_28_in_addexpr311); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleaddexprEx;
            	        }

            	        char_literal26_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal26));
            	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, char_literal26_tree, root_0));

            	        FOLLOWPUSH(FOLLOW_mulexpr_in_addexpr314);
            	        mulexpr27=mulexpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleaddexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, mulexpr27.tree);

            	    }
            	    break;
            	case 2:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:50:37: '-' mulexpr
            	    {
            	        char_literal28 = (pANTLR3_COMMON_TOKEN) MATCHT(29, &FOLLOW_29_in_addexpr318); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleaddexprEx;
            	        }

            	        char_literal28_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal28));
            	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, char_literal28_tree, root_0));

            	        FOLLOWPUSH(FOLLOW_mulexpr_in_addexpr321);
            	        mulexpr29=mulexpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleaddexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, mulexpr29.tree);

            	    }
            	    break;

            	default:
            	    goto loop10;	/* break out of the loop */
            	    break;
                }
            }
            loop10: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleaddexprEx; /* Prevent compiler warnings */
    ruleaddexprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end addexpr */

/** 
 * $ANTLR start mulexpr
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:52:1: mulexpr : atom ( '*' atom | '/' atom )* ;
 */
static islParser_mulexpr_return
mulexpr(pislParser ctx)
{   
    islParser_mulexpr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal31;
    pANTLR3_COMMON_TOKEN    char_literal33;
    islParser_atom_return atom30;
    #undef	RETURN_TYPE_atom30
    #define	RETURN_TYPE_atom30 islParser_atom_return

    islParser_atom_return atom32;
    #undef	RETURN_TYPE_atom32
    #define	RETURN_TYPE_atom32 islParser_atom_return

    islParser_atom_return atom34;
    #undef	RETURN_TYPE_atom34
    #define	RETURN_TYPE_atom34 islParser_atom_return

    pANTLR3_BASE_TREE char_literal31_tree;
    pANTLR3_BASE_TREE char_literal33_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    char_literal31       = NULL;
    char_literal33       = NULL;
    atom30.tree = NULL;

    atom32.tree = NULL;

    atom34.tree = NULL;

    retval.start = LT(1);

    char_literal31_tree   = NULL;
    char_literal33_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:52:9: ( atom ( '*' atom | '/' atom )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:52:11: atom ( '*' atom | '/' atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_atom_in_mulexpr331);
            atom30=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemulexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom30.tree);

            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:52:16: ( '*' atom | '/' atom )*

            for (;;)
            {
                int alt11=3;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA11_0 = LA(1);
                    if ( (LA11_0 == 30) ) 
                    {
                        alt11=1;
                    }
                    else if ( (LA11_0 == 31) ) 
                    {
                        alt11=2;
                    }

                }
                switch (alt11) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:52:17: '*' atom
            	    {
            	        char_literal31 = (pANTLR3_COMMON_TOKEN) MATCHT(30, &FOLLOW_30_in_mulexpr334); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemulexprEx;
            	        }

            	        char_literal31_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal31));
            	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, char_literal31_tree, root_0));

            	        FOLLOWPUSH(FOLLOW_atom_in_mulexpr337);
            	        atom32=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemulexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom32.tree);

            	    }
            	    break;
            	case 2:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:52:29: '/' atom
            	    {
            	        char_literal33 = (pANTLR3_COMMON_TOKEN) MATCHT(31, &FOLLOW_31_in_mulexpr341); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemulexprEx;
            	        }

            	        char_literal33_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, char_literal33));
            	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, char_literal33_tree, root_0));

            	        FOLLOWPUSH(FOLLOW_atom_in_mulexpr344);
            	        atom34=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemulexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom34.tree);

            	    }
            	    break;

            	default:
            	    goto loop11;	/* break out of the loop */
            	    break;
                }
            }
            loop11: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulemulexprEx; /* Prevent compiler warnings */
    rulemulexprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end mulexpr */

/** 
 * $ANTLR start atom
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:54:1: atom : ( id | FLOAT | INTEGER | STRING | LPAREN ( list_or_expr )? RPAREN );
 */
static islParser_atom_return
atom(pislParser ctx)
{   
    islParser_atom_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    FLOAT36;
    pANTLR3_COMMON_TOKEN    INTEGER37;
    pANTLR3_COMMON_TOKEN    STRING38;
    pANTLR3_COMMON_TOKEN    LPAREN39;
    pANTLR3_COMMON_TOKEN    RPAREN41;
    islParser_id_return id35;
    #undef	RETURN_TYPE_id35
    #define	RETURN_TYPE_id35 islParser_id_return

    islParser_list_or_expr_return list_or_expr40;
    #undef	RETURN_TYPE_list_or_expr40
    #define	RETURN_TYPE_list_or_expr40 islParser_list_or_expr_return

    pANTLR3_BASE_TREE FLOAT36_tree;
    pANTLR3_BASE_TREE INTEGER37_tree;
    pANTLR3_BASE_TREE STRING38_tree;
    pANTLR3_BASE_TREE LPAREN39_tree;
    pANTLR3_BASE_TREE RPAREN41_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    FLOAT36       = NULL;
    INTEGER37       = NULL;
    STRING38       = NULL;
    LPAREN39       = NULL;
    RPAREN41       = NULL;
    id35.tree = NULL;

    list_or_expr40.tree = NULL;

    retval.start = LT(1);

    FLOAT36_tree   = NULL;
    INTEGER37_tree   = NULL;
    STRING38_tree   = NULL;
    LPAREN39_tree   = NULL;
    RPAREN41_tree   = NULL;
    retval.tree  = NULL;
    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:54:6: ( id | FLOAT | INTEGER | STRING | LPAREN ( list_or_expr )? RPAREN )
            
            ANTLR3_UINT32 alt13;

            alt13=5;

            switch ( LA(1) ) 
            {
            case NAME:
            	{
            		alt13=1;
            	}
                break;
            case FLOAT:
            	{
            		alt13=2;
            	}
                break;
            case INTEGER:
            	{
            		alt13=3;
            	}
                break;
            case STRING:
            	{
            		alt13=4;
            	}
                break;
            case LPAREN:
            	{
            		alt13=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 13;
                EXCEPTION->state        = 0;


                goto ruleatomEx;
            }

            switch (alt13) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:55:7: id
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_id_in_atom369);
        	        id35=id(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, id35.tree);

        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:56:7: FLOAT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FLOAT36 = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_atom377); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        FLOAT36_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, FLOAT36));
        	        ADAPTOR->addChild(ADAPTOR, root_0, FLOAT36_tree);


        	    }
        	    break;
        	case 3:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:57:7: INTEGER
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        INTEGER37 = (pANTLR3_COMMON_TOKEN) MATCHT(INTEGER, &FOLLOW_INTEGER_in_atom385); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INTEGER37_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INTEGER37));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INTEGER37_tree);


        	    }
        	    break;
        	case 4:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:58:7: STRING
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        STRING38 = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_atom393); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        STRING38_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, STRING38));
        	        ADAPTOR->addChild(ADAPTOR, root_0, STRING38_tree);


        	    }
        	    break;
        	case 5:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:59:7: LPAREN ( list_or_expr )? RPAREN
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        LPAREN39 = (pANTLR3_COMMON_TOKEN) MATCHT(LPAREN, &FOLLOW_LPAREN_in_atom401); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        LPAREN39_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, LPAREN39));
        	        ADAPTOR->addChild(ADAPTOR, root_0, LPAREN39_tree);


        	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:59:14: ( list_or_expr )?
        	        {
        	            int alt12=2;
        	            {
        	                int LA12_0 = LA(1);
        	                if ( (((LA12_0 >= FLOAT) && (LA12_0 <= LPAREN)) || LA12_0 == NAME) ) 
        	                {
        	                    alt12=1;
        	                }
        	            }
        	            switch (alt12) 
        	            {
        	        	case 1:
        	        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:59:14: list_or_expr
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_list_or_expr_in_atom403);
        	        	        list_or_expr40=list_or_expr(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleatomEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, list_or_expr40.tree);

        	        	    }
        	        	    break;

        	            }
        	        }
        	        RPAREN41 = (pANTLR3_COMMON_TOKEN) MATCHT(RPAREN, &FOLLOW_RPAREN_in_atom406); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        RPAREN41_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, RPAREN41));
        	        ADAPTOR->addChild(ADAPTOR, root_0, RPAREN41_tree);


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end atom */

/** 
 * $ANTLR start list_or_expr
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:62:1: list_or_expr : addexpr ( ( COMMA )? addexpr )* ;
 */
static islParser_list_or_expr_return
list_or_expr(pislParser ctx)
{   
    islParser_list_or_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    COMMA43;
    islParser_addexpr_return addexpr42;
    #undef	RETURN_TYPE_addexpr42
    #define	RETURN_TYPE_addexpr42 islParser_addexpr_return

    islParser_addexpr_return addexpr44;
    #undef	RETURN_TYPE_addexpr44
    #define	RETURN_TYPE_addexpr44 islParser_addexpr_return

    pANTLR3_BASE_TREE COMMA43_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    COMMA43       = NULL;
    addexpr42.tree = NULL;

    addexpr44.tree = NULL;

    retval.start = LT(1);

    COMMA43_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:63:5: ( addexpr ( ( COMMA )? addexpr )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:63:7: addexpr ( ( COMMA )? addexpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_addexpr_in_list_or_expr430);
            addexpr42=addexpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulelist_or_exprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, addexpr42.tree);

            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:63:15: ( ( COMMA )? addexpr )*

            for (;;)
            {
                int alt15=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA15_0 = LA(1);
                    if ( (((LA15_0 >= FLOAT) && (LA15_0 <= LPAREN)) || ((LA15_0 >= COMMA) && (LA15_0 <= NAME))) ) 
                    {
                        alt15=1;
                    }

                }
                switch (alt15) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:63:16: ( COMMA )? addexpr
            	    {

            	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:63:16: ( COMMA )?
            	        {
            	            int alt14=2;
            	            {
            	                int LA14_0 = LA(1);
            	                if ( (LA14_0 == COMMA) ) 
            	                {
            	                    alt14=1;
            	                }
            	            }
            	            switch (alt14) 
            	            {
            	        	case 1:
            	        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:63:16: COMMA
            	        	    {
            	        	        COMMA43 = (pANTLR3_COMMON_TOKEN) MATCHT(COMMA, &FOLLOW_COMMA_in_list_or_expr433); 
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulelist_or_exprEx;
            	        	        }

            	        	        COMMA43_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, COMMA43));
            	        	        ADAPTOR->addChild(ADAPTOR, root_0, COMMA43_tree);


            	        	    }
            	        	    break;

            	            }
            	        }
            	        FOLLOWPUSH(FOLLOW_addexpr_in_list_or_expr436);
            	        addexpr44=addexpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulelist_or_exprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, addexpr44.tree);

            	    }
            	    break;

            	default:
            	    goto loop15;	/* break out of the loop */
            	    break;
                }
            }
            loop15: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulelist_or_exprEx; /* Prevent compiler warnings */
    rulelist_or_exprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end list_or_expr */

/** 
 * $ANTLR start id
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:66:1: id : NAME ( DOT NAME )* ;
 */
static islParser_id_return
id(pislParser ctx)
{   
    islParser_id_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NAME45;
    pANTLR3_COMMON_TOKEN    DOT46;
    pANTLR3_COMMON_TOKEN    NAME47;

    pANTLR3_BASE_TREE NAME45_tree;
    pANTLR3_BASE_TREE DOT46_tree;
    pANTLR3_BASE_TREE NAME47_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    NAME45       = NULL;
    DOT46       = NULL;
    NAME47       = NULL;
    retval.start = LT(1);

    NAME45_tree   = NULL;
    DOT46_tree   = NULL;
    NAME47_tree   = NULL;
    retval.tree  = NULL;
    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:66:4: ( NAME ( DOT NAME )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:66:6: NAME ( DOT NAME )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            NAME45 = (pANTLR3_COMMON_TOKEN) MATCHT(NAME, &FOLLOW_NAME_in_id460); 
            if  (HASEXCEPTION())
            {
                goto ruleidEx;
            }

            NAME45_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, NAME45));
            ADAPTOR->addChild(ADAPTOR, root_0, NAME45_tree);


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:66:11: ( DOT NAME )*

            for (;;)
            {
                int alt16=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA16_0 = LA(1);
                    if ( (LA16_0 == DOT) ) 
                    {
                        alt16=1;
                    }

                }
                switch (alt16) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:66:12: DOT NAME
            	    {
            	        DOT46 = (pANTLR3_COMMON_TOKEN) MATCHT(DOT, &FOLLOW_DOT_in_id463); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidEx;
            	        }

            	        DOT46_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DOT46));
            	        ADAPTOR->addChild(ADAPTOR, root_0, DOT46_tree);

            	        NAME47 = (pANTLR3_COMMON_TOKEN) MATCHT(NAME, &FOLLOW_NAME_in_id465); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidEx;
            	        }

            	        NAME47_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, NAME47));
            	        ADAPTOR->addChild(ADAPTOR, root_0, NAME47_tree);


            	    }
            	    break;

            	default:
            	    goto loop16;	/* break out of the loop */
            	    break;
                }
            }
            loop16: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidEx; /* Prevent compiler warnings */
    ruleidEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end id */

/** 
 * $ANTLR start idinherit
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:67:1: idinherit : ( NAME | ( NAME COLON NAME ) );
 */
static islParser_idinherit_return
idinherit(pislParser ctx)
{   
    islParser_idinherit_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NAME48;
    pANTLR3_COMMON_TOKEN    NAME49;
    pANTLR3_COMMON_TOKEN    COLON50;
    pANTLR3_COMMON_TOKEN    NAME51;

    pANTLR3_BASE_TREE NAME48_tree;
    pANTLR3_BASE_TREE NAME49_tree;
    pANTLR3_BASE_TREE COLON50_tree;
    pANTLR3_BASE_TREE NAME51_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    NAME48       = NULL;
    NAME49       = NULL;
    COLON50       = NULL;
    NAME51       = NULL;
    retval.start = LT(1);

    NAME48_tree   = NULL;
    NAME49_tree   = NULL;
    COLON50_tree   = NULL;
    NAME51_tree   = NULL;
    retval.tree  = NULL;
    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:67:11: ( NAME | ( NAME COLON NAME ) )
            
            ANTLR3_UINT32 alt17;

            alt17=2;


            {
                int LA17_0 = LA(1);
                if ( (LA17_0 == NAME) ) 
                {

                    {
                        int LA17_1 = LA(2);
                        if ( (LA17_1 == COLON) ) 
                        {
                            alt17=2;
                        }
                        else if ( (LA17_1 == 22) ) 
                        {
                            alt17=1;
                        }
                        else 
                        {
                        
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 17;
                            EXCEPTION->state        = 1;


                            goto ruleidinheritEx;
                        }
                    }
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 17;
                    EXCEPTION->state        = 0;


                    goto ruleidinheritEx;
                }
            }
            switch (alt17) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:67:13: NAME
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        NAME48 = (pANTLR3_COMMON_TOKEN) MATCHT(NAME, &FOLLOW_NAME_in_idinherit474); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidinheritEx;
        	        }

        	        NAME48_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, NAME48));
        	        ADAPTOR->addChild(ADAPTOR, root_0, NAME48_tree);


        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:67:20: ( NAME COLON NAME )
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:67:20: ( NAME COLON NAME )
        	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\isl.g:67:21: NAME COLON NAME
        	        {
        	            NAME49 = (pANTLR3_COMMON_TOKEN) MATCHT(NAME, &FOLLOW_NAME_in_idinherit479); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleidinheritEx;
        	            }

        	            NAME49_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, NAME49));
        	            ADAPTOR->addChild(ADAPTOR, root_0, NAME49_tree);

        	            COLON50 = (pANTLR3_COMMON_TOKEN) MATCHT(COLON, &FOLLOW_COLON_in_idinherit481); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleidinheritEx;
        	            }

        	            COLON50_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, COLON50));
        	            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, COLON50_tree, root_0));

        	            NAME51 = (pANTLR3_COMMON_TOKEN) MATCHT(NAME, &FOLLOW_NAME_in_idinherit484); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleidinheritEx;
        	            }

        	            NAME51_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, NAME51));
        	            ADAPTOR->addChild(ADAPTOR, root_0, NAME51_tree);


        	        }


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleidinheritEx; /* Prevent compiler warnings */
    ruleidinheritEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);


    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
        retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
    }

    return retval;
}
/* $ANTLR end idinherit */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
