/** \file
 *  This C source file was generated by $ANTLR version 3.1.1
 *
 *     -  From the grammar source file : C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g
 *     -                            On : 2008-10-10 02:04:51
 *     -           for the tree parser : islWalkerTreeParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "islWalker.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pislWalker_##scope##_SCOPE
#define SCOPE_STACK(scope)  pislWalker_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pislWalker_##scope##Top
#define	SCOPE_SIZE(scope)			(ctx->SCOPE_STACK(scope)->size(ctx->SCOPE_STACK(scope)))
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO		
#undef		SEEK    
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   islWalkerTokenNames[23+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "FLOAT",
        (pANTLR3_UINT8) "INTEGER",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "LPAREN",
        (pANTLR3_UINT8) "RPAREN",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "NAME",
        (pANTLR3_UINT8) "DOT",
        (pANTLR3_UINT8) "COLON",
        (pANTLR3_UINT8) "MCMT",
        (pANTLR3_UINT8) "SCMT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'",
        (pANTLR3_UINT8) "'color'",
        (pANTLR3_UINT8) "'material'",
        (pANTLR3_UINT8) "'config'",
        (pANTLR3_UINT8) "'='",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'+'",
        (pANTLR3_UINT8) "'-'",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "'/'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static void	script    (pislWalker ctx);
static void	statements    (pislWalker ctx);
static void	classdef    (pislWalker ctx);
static void	classType    (pislWalker ctx);
static void	classColor    (pislWalker ctx);
static void	classMaterial    (pislWalker ctx);
static void	classConfig    (pislWalker ctx);
static void	cstatements    (pislWalker ctx);
static void	assignment    (pislWalker ctx);
static void	expr    (pislWalker ctx);
static void	addsubexpr    (pislWalker ctx);
static void	muldivexpr    (pislWalker ctx);
static void	atom    (pislWalker ctx);
static void	list_or_expr    (pislWalker ctx);
static void	id    (pislWalker ctx);
static void	idinherit    (pislWalker ctx);
static void	islWalkerFree(pislWalker ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new islWalker parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pislWalker
islWalkerNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return islWalkerNewSSD(instream, NULL);
}

/** \brief Create a new islWalker parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pislWalker
islWalkerNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pislWalker ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pislWalker) ANTLR3_CALLOC(1, sizeof(islWalker));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in islWalker.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);
    /* Install the implementation of our islWalker interface
     */
    ctx->script	= script;
    ctx->statements	= statements;
    ctx->classdef	= classdef;
    ctx->classType	= classType;
    ctx->classColor	= classColor;
    ctx->classMaterial	= classMaterial;
    ctx->classConfig	= classConfig;
    ctx->cstatements	= cstatements;
    ctx->assignment	= assignment;
    ctx->expr	= expr;
    ctx->addsubexpr	= addsubexpr;
    ctx->muldivexpr	= muldivexpr;
    ctx->atom	= atom;
    ctx->list_or_expr	= list_or_expr;
    ctx->id	= id;
    ctx->idinherit	= idinherit;
    ctx->free			= islWalkerFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = islWalkerTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 islWalkerFree(pislWalker ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this tree parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return islWalkerTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_statements_in_script51  */
static	ANTLR3_BITWORD FOLLOW_statements_in_script51_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C0402) };
static  ANTLR3_BITSET_LIST FOLLOW_statements_in_script51	= { FOLLOW_statements_in_script51_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classdef_in_statements72  */
static	ANTLR3_BITWORD FOLLOW_classdef_in_statements72_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classdef_in_statements72	= { FOLLOW_classdef_in_statements72_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_statements80  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_statements80_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_statements80	= { FOLLOW_assignment_in_statements80_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classType_in_classdef96  */
static	ANTLR3_BITWORD FOLLOW_classType_in_classdef96_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_classType_in_classdef96	= { FOLLOW_classType_in_classdef96_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_classdef98  */
static	ANTLR3_BITWORD FOLLOW_16_in_classdef98_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001E0400) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_classdef98	= { FOLLOW_16_in_classdef98_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_cstatements_in_classdef100  */
static	ANTLR3_BITWORD FOLLOW_cstatements_in_classdef100_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001E0400) };
static  ANTLR3_BITSET_LIST FOLLOW_cstatements_in_classdef100	= { FOLLOW_cstatements_in_classdef100_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_classdef103  */
static	ANTLR3_BITWORD FOLLOW_17_in_classdef103_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_classdef103	= { FOLLOW_17_in_classdef103_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classColor_in_classType119  */
static	ANTLR3_BITWORD FOLLOW_classColor_in_classType119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classColor_in_classType119	= { FOLLOW_classColor_in_classType119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classMaterial_in_classType129  */
static	ANTLR3_BITWORD FOLLOW_classMaterial_in_classType129_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classMaterial_in_classType129	= { FOLLOW_classMaterial_in_classType129_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classConfig_in_classType139  */
static	ANTLR3_BITWORD FOLLOW_classConfig_in_classType139_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classConfig_in_classType139	= { FOLLOW_classConfig_in_classType139_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_classColor156  */
static	ANTLR3_BITWORD FOLLOW_18_in_classColor156_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_classColor156	= { FOLLOW_18_in_classColor156_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idinherit_in_classColor158  */
static	ANTLR3_BITWORD FOLLOW_idinherit_in_classColor158_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idinherit_in_classColor158	= { FOLLOW_idinherit_in_classColor158_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_classMaterial166  */
static	ANTLR3_BITWORD FOLLOW_19_in_classMaterial166_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_classMaterial166	= { FOLLOW_19_in_classMaterial166_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idinherit_in_classMaterial168  */
static	ANTLR3_BITWORD FOLLOW_idinherit_in_classMaterial168_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idinherit_in_classMaterial168	= { FOLLOW_idinherit_in_classMaterial168_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_classConfig176  */
static	ANTLR3_BITWORD FOLLOW_20_in_classConfig176_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_classConfig176	= { FOLLOW_20_in_classConfig176_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_idinherit_in_classConfig178  */
static	ANTLR3_BITWORD FOLLOW_idinherit_in_classConfig178_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_idinherit_in_classConfig178	= { FOLLOW_idinherit_in_classConfig178_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classdef_in_cstatements195  */
static	ANTLR3_BITWORD FOLLOW_classdef_in_cstatements195_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_classdef_in_cstatements195	= { FOLLOW_classdef_in_cstatements195_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignment_in_cstatements203  */
static	ANTLR3_BITWORD FOLLOW_assignment_in_cstatements203_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_assignment_in_cstatements203	= { FOLLOW_assignment_in_cstatements203_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_id_in_assignment215  */
static	ANTLR3_BITWORD FOLLOW_id_in_assignment215_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000201000) };
static  ANTLR3_BITSET_LIST FOLLOW_id_in_assignment215	= { FOLLOW_id_in_assignment215_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_assignment217  */
static	ANTLR3_BITWORD FOLLOW_set_in_assignment217_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C04F0) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_assignment217	= { FOLLOW_set_in_assignment217_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_assignment226  */
static	ANTLR3_BITWORD FOLLOW_expr_in_assignment226_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_assignment226	= { FOLLOW_expr_in_assignment226_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_classdef_in_assignment230  */
static	ANTLR3_BITWORD FOLLOW_classdef_in_assignment230_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_classdef_in_assignment230	= { FOLLOW_classdef_in_assignment230_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_assignment233  */
static	ANTLR3_BITWORD FOLLOW_22_in_assignment233_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_assignment233	= { FOLLOW_22_in_assignment233_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addsubexpr_in_expr250  */
static	ANTLR3_BITWORD FOLLOW_addsubexpr_in_expr250_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_addsubexpr_in_expr250	= { FOLLOW_addsubexpr_in_expr250_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_muldivexpr_in_addsubexpr272  */
static	ANTLR3_BITWORD FOLLOW_muldivexpr_in_addsubexpr272_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001800002) };
static  ANTLR3_BITSET_LIST FOLLOW_muldivexpr_in_addsubexpr272	= { FOLLOW_muldivexpr_in_addsubexpr272_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_addsubexpr275  */
static	ANTLR3_BITWORD FOLLOW_set_in_addsubexpr275_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C04F0) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_addsubexpr275	= { FOLLOW_set_in_addsubexpr275_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_muldivexpr_in_addsubexpr283  */
static	ANTLR3_BITWORD FOLLOW_muldivexpr_in_addsubexpr283_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001800002) };
static  ANTLR3_BITSET_LIST FOLLOW_muldivexpr_in_addsubexpr283	= { FOLLOW_muldivexpr_in_addsubexpr283_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_muldivexpr310  */
static	ANTLR3_BITWORD FOLLOW_atom_in_muldivexpr310_bits[]	= { ANTLR3_UINT64_LIT(0x0000000006000002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_muldivexpr310	= { FOLLOW_atom_in_muldivexpr310_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_muldivexpr313  */
static	ANTLR3_BITWORD FOLLOW_set_in_muldivexpr313_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C04F0) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_muldivexpr313	= { FOLLOW_set_in_muldivexpr313_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_muldivexpr321  */
static	ANTLR3_BITWORD FOLLOW_atom_in_muldivexpr321_bits[]	= { ANTLR3_UINT64_LIT(0x0000000006000002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_muldivexpr321	= { FOLLOW_atom_in_muldivexpr321_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_id_in_atom347  */
static	ANTLR3_BITWORD FOLLOW_id_in_atom347_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_id_in_atom347	= { FOLLOW_id_in_atom347_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_atom355  */
static	ANTLR3_BITWORD FOLLOW_FLOAT_in_atom355_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_atom355	= { FOLLOW_FLOAT_in_atom355_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INTEGER_in_atom363  */
static	ANTLR3_BITWORD FOLLOW_INTEGER_in_atom363_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INTEGER_in_atom363	= { FOLLOW_INTEGER_in_atom363_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_atom371  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_atom371_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_atom371	= { FOLLOW_STRING_in_atom371_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAREN_in_atom379  */
static	ANTLR3_BITWORD FOLLOW_LPAREN_in_atom379_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C05F0) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAREN_in_atom379	= { FOLLOW_LPAREN_in_atom379_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_list_or_expr_in_atom381  */
static	ANTLR3_BITWORD FOLLOW_list_or_expr_in_atom381_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_list_or_expr_in_atom381	= { FOLLOW_list_or_expr_in_atom381_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_atom384  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_atom384_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_atom384	= { FOLLOW_RPAREN_in_atom384_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_list_or_expr408  */
static	ANTLR3_BITWORD FOLLOW_expr_in_list_or_expr408_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C06F2) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_list_or_expr408	= { FOLLOW_expr_in_list_or_expr408_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COMMA_in_list_or_expr411  */
static	ANTLR3_BITWORD FOLLOW_COMMA_in_list_or_expr411_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C04F0) };
static  ANTLR3_BITSET_LIST FOLLOW_COMMA_in_list_or_expr411	= { FOLLOW_COMMA_in_list_or_expr411_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_list_or_expr414  */
static	ANTLR3_BITWORD FOLLOW_expr_in_list_or_expr414_bits[]	= { ANTLR3_UINT64_LIT(0x00000000001C06F2) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_list_or_expr414	= { FOLLOW_expr_in_list_or_expr414_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_id438  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_id438_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_id438	= { FOLLOW_NAME_in_id438_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DOT_in_id441  */
static	ANTLR3_BITWORD FOLLOW_DOT_in_id441_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_DOT_in_id441	= { FOLLOW_DOT_in_id441_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_id443  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_id443_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000802) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_id443	= { FOLLOW_NAME_in_id443_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_idinherit452  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_idinherit452_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_idinherit452	= { FOLLOW_NAME_in_idinherit452_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_idinherit457  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_idinherit457_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_idinherit457	= { FOLLOW_NAME_in_idinherit457_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COLON_in_idinherit459  */
static	ANTLR3_BITWORD FOLLOW_COLON_in_idinherit459_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_COLON_in_idinherit459	= { FOLLOW_COLON_in_idinherit459_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NAME_in_idinherit461  */
static	ANTLR3_BITWORD FOLLOW_NAME_in_idinherit461_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NAME_in_idinherit461	= { FOLLOW_NAME_in_idinherit461_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start script
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:10:1: script : ( statements )+ ;
 */
static void
script(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:10:8: ( ( statements )+ )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:10:10: ( statements )+
        {
            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:10:10: ( statements )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	{
            	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
            	    */
            	    int LA1_0 = LA(1);
            	    if ( (LA1_0 == NAME || ((LA1_0 >= 18) && (LA1_0 <= 20))) ) 
            	    {
            	        alt1=1;
            	    }

            	}
            	switch (alt1) 
            	{
            	    case 1:
            	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:10:10: statements
            	        {
            	            FOLLOWPUSH(FOLLOW_statements_in_script51);
            	            statements(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulescriptEx;
            	            }


            	        }
            	        break;

            	    default:
            	    
            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulescriptEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulescriptEx; /* Prevent compiler warnings */
    rulescriptEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end script */

/** 
 * $ANTLR start statements
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:13:1: statements : ( classdef | assignment );
 */
static void
statements(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:13:12: ( classdef | assignment )
            
            ANTLR3_UINT32 alt2;

            alt2=2;


            {
                int LA2_0 = LA(1);
                if ( (((LA2_0 >= 18) && (LA2_0 <= 20))) ) 
                {
                    alt2=1;
                }
                else if ( (LA2_0 == NAME) ) 
                {
                    alt2=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 2;
                    EXCEPTION->state        = 0;


                    goto rulestatementsEx;
                }
            }
            switch (alt2) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:14:7: classdef
        	    {
        	        FOLLOWPUSH(FOLLOW_classdef_in_statements72);
        	        classdef(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementsEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:15:7: assignment
        	    {
        	        FOLLOWPUSH(FOLLOW_assignment_in_statements80);
        	        assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatementsEx;
        	        }


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulestatementsEx; /* Prevent compiler warnings */
    rulestatementsEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end statements */

/** 
 * $ANTLR start classdef
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:18:1: classdef : classType '{' ( cstatements )* '}' ;
 */
static void
classdef(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:18:9: ( classType '{' ( cstatements )* '}' )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:19:5: classType '{' ( cstatements )* '}'
        {
            FOLLOWPUSH(FOLLOW_classType_in_classdef96);
            classType(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleclassdefEx;
            }

             MATCHT(16, &FOLLOW_16_in_classdef98); 
            if  (HASEXCEPTION())
            {
                goto ruleclassdefEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:19:19: ( cstatements )*

            for (;;)
            {
                int alt3=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA3_0 = LA(1);
                    if ( (LA3_0 == NAME || ((LA3_0 >= 18) && (LA3_0 <= 20))) ) 
                    {
                        alt3=1;
                    }

                }
                switch (alt3) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:19:19: cstatements
            	    {
            	        FOLLOWPUSH(FOLLOW_cstatements_in_classdef100);
            	        cstatements(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassdefEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */

             MATCHT(17, &FOLLOW_17_in_classdef103); 
            if  (HASEXCEPTION())
            {
                goto ruleclassdefEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassdefEx; /* Prevent compiler warnings */
    ruleclassdefEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end classdef */

/** 
 * $ANTLR start classType
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:21:1: classType : ( classColor | classMaterial | classConfig );
 */
static void
classType(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:21:11: ( classColor | classMaterial | classConfig )
            
            ANTLR3_UINT32 alt4;

            alt4=3;

            switch ( LA(1) ) 
            {
            case 18:
            	{
            		alt4=1;
            	}
                break;
            case 19:
            	{
            		alt4=2;
            	}
                break;
            case 20:
            	{
            		alt4=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 4;
                EXCEPTION->state        = 0;


                goto ruleclassTypeEx;
            }

            switch (alt4) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:22:9: classColor
        	    {
        	        FOLLOWPUSH(FOLLOW_classColor_in_classType119);
        	        classColor(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleclassTypeEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:23:9: classMaterial
        	    {
        	        FOLLOWPUSH(FOLLOW_classMaterial_in_classType129);
        	        classMaterial(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleclassTypeEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:24:9: classConfig
        	    {
        	        FOLLOWPUSH(FOLLOW_classConfig_in_classType139);
        	        classConfig(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleclassTypeEx;
        	        }


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassTypeEx; /* Prevent compiler warnings */
    ruleclassTypeEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end classType */

/** 
 * $ANTLR start classColor
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:27:1: classColor : 'color' ( idinherit )? ;
 */
static void
classColor(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:27:12: ( 'color' ( idinherit )? )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:27:14: 'color' ( idinherit )?
        {
             MATCHT(18, &FOLLOW_18_in_classColor156); 
            if  (HASEXCEPTION())
            {
                goto ruleclassColorEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:27:22: ( idinherit )?
            {
                int alt5=2;
                {
                    int LA5_0 = LA(1);
                    if ( (LA5_0 == NAME) ) 
                    {
                        alt5=1;
                    }
                }
                switch (alt5) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:27:22: idinherit
            	    {
            	        FOLLOWPUSH(FOLLOW_idinherit_in_classColor158);
            	        idinherit(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassColorEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassColorEx; /* Prevent compiler warnings */
    ruleclassColorEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end classColor */

/** 
 * $ANTLR start classMaterial
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:28:1: classMaterial : 'material' ( idinherit )? ;
 */
static void
classMaterial(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:28:15: ( 'material' ( idinherit )? )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:28:17: 'material' ( idinherit )?
        {
             MATCHT(19, &FOLLOW_19_in_classMaterial166); 
            if  (HASEXCEPTION())
            {
                goto ruleclassMaterialEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:28:28: ( idinherit )?
            {
                int alt6=2;
                {
                    int LA6_0 = LA(1);
                    if ( (LA6_0 == NAME) ) 
                    {
                        alt6=1;
                    }
                }
                switch (alt6) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:28:28: idinherit
            	    {
            	        FOLLOWPUSH(FOLLOW_idinherit_in_classMaterial168);
            	        idinherit(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassMaterialEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassMaterialEx; /* Prevent compiler warnings */
    ruleclassMaterialEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end classMaterial */

/** 
 * $ANTLR start classConfig
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:29:1: classConfig : 'config' ( idinherit )? ;
 */
static void
classConfig(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:29:13: ( 'config' ( idinherit )? )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:29:15: 'config' ( idinherit )?
        {
             MATCHT(20, &FOLLOW_20_in_classConfig176); 
            if  (HASEXCEPTION())
            {
                goto ruleclassConfigEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:29:24: ( idinherit )?
            {
                int alt7=2;
                {
                    int LA7_0 = LA(1);
                    if ( (LA7_0 == NAME) ) 
                    {
                        alt7=1;
                    }
                }
                switch (alt7) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:29:24: idinherit
            	    {
            	        FOLLOWPUSH(FOLLOW_idinherit_in_classConfig178);
            	        idinherit(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleclassConfigEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleclassConfigEx; /* Prevent compiler warnings */
    ruleclassConfigEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end classConfig */

/** 
 * $ANTLR start cstatements
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:31:1: cstatements : ( classdef | assignment );
 */
static void
cstatements(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:31:12: ( classdef | assignment )
            
            ANTLR3_UINT32 alt8;

            alt8=2;


            {
                int LA8_0 = LA(1);
                if ( (((LA8_0 >= 18) && (LA8_0 <= 20))) ) 
                {
                    alt8=1;
                }
                else if ( (LA8_0 == NAME) ) 
                {
                    alt8=2;
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 8;
                    EXCEPTION->state        = 0;


                    goto rulecstatementsEx;
                }
            }
            switch (alt8) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:32:9: classdef
        	    {
        	        FOLLOWPUSH(FOLLOW_classdef_in_cstatements195);
        	        classdef(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecstatementsEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:33:7: assignment
        	    {
        	        FOLLOWPUSH(FOLLOW_assignment_in_cstatements203);
        	        assignment(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecstatementsEx;
        	        }


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulecstatementsEx; /* Prevent compiler warnings */
    rulecstatementsEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end cstatements */

/** 
 * $ANTLR start assignment
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:35:1: assignment : id ( '=' | ':' ) ( expr | classdef ) ';' ;
 */
static void
assignment(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:35:12: ( id ( '=' | ':' ) ( expr | classdef ) ';' )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:36:5: id ( '=' | ':' ) ( expr | classdef ) ';'
        {
            FOLLOWPUSH(FOLLOW_id_in_assignment215);
            id(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }

            if ( LA(1) == COLON || LA(1) == 21 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_assignment217);    goto ruleassignmentEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:36:20: ( expr | classdef )
            {
                int alt9=2;

                {
                    int LA9_0 = LA(1);
                    if ( (((LA9_0 >= FLOAT) && (LA9_0 <= LPAREN)) || LA9_0 == NAME) ) 
                    {
                        alt9=1;
                    }
                    else if ( (((LA9_0 >= 18) && (LA9_0 <= 20))) ) 
                    {
                        alt9=2;
                    }
                    else 
                    {
                    
                        CONSTRUCTEX();
                        EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                        EXCEPTION->message      = (void *)"";
                        EXCEPTION->decisionNum  = 9;
                        EXCEPTION->state        = 0;


                        goto ruleassignmentEx;
                    }
                }
                switch (alt9) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:36:21: expr
            	    {
            	        FOLLOWPUSH(FOLLOW_expr_in_assignment226);
            	        expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }


            	    }
            	    break;
            	case 2:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:36:28: classdef
            	    {
            	        FOLLOWPUSH(FOLLOW_classdef_in_assignment230);
            	        classdef(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleassignmentEx;
            	        }


            	    }
            	    break;

                }
            }
             MATCHT(22, &FOLLOW_22_in_assignment233); 
            if  (HASEXCEPTION())
            {
                goto ruleassignmentEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleassignmentEx; /* Prevent compiler warnings */
    ruleassignmentEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end assignment */

/** 
 * $ANTLR start expr
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:39:1: expr : addsubexpr ;
 */
static void
expr(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:39:6: ( addsubexpr )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:39:8: addsubexpr
        {
            FOLLOWPUSH(FOLLOW_addsubexpr_in_expr250);
            addsubexpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start addsubexpr
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:42:1: addsubexpr : muldivexpr ( ( '+' | '-' ) muldivexpr )* ;
 */
static void
addsubexpr(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:42:12: ( muldivexpr ( ( '+' | '-' ) muldivexpr )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:43:5: muldivexpr ( ( '+' | '-' ) muldivexpr )*
        {
            FOLLOWPUSH(FOLLOW_muldivexpr_in_addsubexpr272);
            muldivexpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleaddsubexprEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:43:16: ( ( '+' | '-' ) muldivexpr )*

            for (;;)
            {
                int alt10=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA10_0 = LA(1);
                    if ( (((LA10_0 >= 23) && (LA10_0 <= 24))) ) 
                    {
                        alt10=1;
                    }

                }
                switch (alt10) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:43:17: ( '+' | '-' ) muldivexpr
            	    {
            	        if ( ((LA(1) >= 23) && (LA(1) <= 24)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_addsubexpr275);    goto ruleaddsubexprEx;
            	        }

            	        FOLLOWPUSH(FOLLOW_muldivexpr_in_addsubexpr283);
            	        muldivexpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleaddsubexprEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop10;	/* break out of the loop */
            	    break;
                }
            }
            loop10: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleaddsubexprEx; /* Prevent compiler warnings */
    ruleaddsubexprEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end addsubexpr */

/** 
 * $ANTLR start muldivexpr
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:46:1: muldivexpr : atom ( ( '*' | '/' ) atom )* ;
 */
static void
muldivexpr(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:46:12: ( atom ( ( '*' | '/' ) atom )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:47:5: atom ( ( '*' | '/' ) atom )*
        {
            FOLLOWPUSH(FOLLOW_atom_in_muldivexpr310);
            atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemuldivexprEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:47:10: ( ( '*' | '/' ) atom )*

            for (;;)
            {
                int alt11=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA11_0 = LA(1);
                    if ( (((LA11_0 >= 25) && (LA11_0 <= 26))) ) 
                    {
                        alt11=1;
                    }

                }
                switch (alt11) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:47:11: ( '*' | '/' ) atom
            	    {
            	        if ( ((LA(1) >= 25) && (LA(1) <= 26)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else 
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            	            RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_muldivexpr313);    goto rulemuldivexprEx;
            	        }

            	        FOLLOWPUSH(FOLLOW_atom_in_muldivexpr321);
            	        atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemuldivexprEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop11;	/* break out of the loop */
            	    break;
                }
            }
            loop11: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulemuldivexprEx; /* Prevent compiler warnings */
    rulemuldivexprEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end muldivexpr */

/** 
 * $ANTLR start atom
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:50:1: atom : ( id | FLOAT | INTEGER | STRING | LPAREN ( list_or_expr )? RPAREN );
 */
static void
atom(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:50:6: ( id | FLOAT | INTEGER | STRING | LPAREN ( list_or_expr )? RPAREN )
            
            ANTLR3_UINT32 alt13;

            alt13=5;

            switch ( LA(1) ) 
            {
            case NAME:
            	{
            		alt13=1;
            	}
                break;
            case FLOAT:
            	{
            		alt13=2;
            	}
                break;
            case INTEGER:
            	{
            		alt13=3;
            	}
                break;
            case STRING:
            	{
            		alt13=4;
            	}
                break;
            case LPAREN:
            	{
            		alt13=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 13;
                EXCEPTION->state        = 0;


                goto ruleatomEx;
            }

            switch (alt13) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:51:7: id
        	    {
        	        FOLLOWPUSH(FOLLOW_id_in_atom347);
        	        id(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:52:7: FLOAT
        	    {
        	         MATCHT(FLOAT, &FOLLOW_FLOAT_in_atom355); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:53:7: INTEGER
        	    {
        	         MATCHT(INTEGER, &FOLLOW_INTEGER_in_atom363); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 4:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:54:7: STRING
        	    {
        	         MATCHT(STRING, &FOLLOW_STRING_in_atom371); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 5:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:55:7: LPAREN ( list_or_expr )? RPAREN
        	    {
        	         MATCHT(LPAREN, &FOLLOW_LPAREN_in_atom379); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:55:14: ( list_or_expr )?
        	        {
        	            int alt12=2;
        	            {
        	                int LA12_0 = LA(1);
        	                if ( (((LA12_0 >= FLOAT) && (LA12_0 <= LPAREN)) || LA12_0 == NAME) ) 
        	                {
        	                    alt12=1;
        	                }
        	            }
        	            switch (alt12) 
        	            {
        	        	case 1:
        	        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:55:14: list_or_expr
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_list_or_expr_in_atom381);
        	        	        list_or_expr(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleatomEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }
        	         MATCHT(RPAREN, &FOLLOW_RPAREN_in_atom384); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end atom */

/** 
 * $ANTLR start list_or_expr
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:58:1: list_or_expr : expr ( ( COMMA )? expr )* ;
 */
static void
list_or_expr(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:59:5: ( expr ( ( COMMA )? expr )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:59:7: expr ( ( COMMA )? expr )*
        {
            FOLLOWPUSH(FOLLOW_expr_in_list_or_expr408);
            expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulelist_or_exprEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:59:12: ( ( COMMA )? expr )*

            for (;;)
            {
                int alt15=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA15_0 = LA(1);
                    if ( (((LA15_0 >= FLOAT) && (LA15_0 <= LPAREN)) || ((LA15_0 >= COMMA) && (LA15_0 <= NAME))) ) 
                    {
                        alt15=1;
                    }

                }
                switch (alt15) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:59:13: ( COMMA )? expr
            	    {

            	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:59:13: ( COMMA )?
            	        {
            	            int alt14=2;
            	            {
            	                int LA14_0 = LA(1);
            	                if ( (LA14_0 == COMMA) ) 
            	                {
            	                    alt14=1;
            	                }
            	            }
            	            switch (alt14) 
            	            {
            	        	case 1:
            	        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:59:13: COMMA
            	        	    {
            	        	         MATCHT(COMMA, &FOLLOW_COMMA_in_list_or_expr411); 
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulelist_or_exprEx;
            	        	        }


            	        	    }
            	        	    break;

            	            }
            	        }
            	        FOLLOWPUSH(FOLLOW_expr_in_list_or_expr414);
            	        expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulelist_or_exprEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop15;	/* break out of the loop */
            	    break;
                }
            }
            loop15: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulelist_or_exprEx; /* Prevent compiler warnings */
    rulelist_or_exprEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end list_or_expr */

/** 
 * $ANTLR start id
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:62:1: id : NAME ( DOT NAME )* ;
 */
static void
id(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:62:4: ( NAME ( DOT NAME )* )
        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:62:6: NAME ( DOT NAME )*
        {
             MATCHT(NAME, &FOLLOW_NAME_in_id438); 
            if  (HASEXCEPTION())
            {
                goto ruleidEx;
            }


            // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:62:11: ( DOT NAME )*

            for (;;)
            {
                int alt16=2;
                {
                   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                    */
                    int LA16_0 = LA(1);
                    if ( (LA16_0 == DOT) ) 
                    {
                        alt16=1;
                    }

                }
                switch (alt16) 
                {
            	case 1:
            	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:62:12: DOT NAME
            	    {
            	         MATCHT(DOT, &FOLLOW_DOT_in_id441); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidEx;
            	        }

            	         MATCHT(NAME, &FOLLOW_NAME_in_id443); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleidEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop16;	/* break out of the loop */
            	    break;
                }
            }
            loop16: ; /* Jump out to here if this rule does not match */


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleidEx; /* Prevent compiler warnings */
    ruleidEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end id */

/** 
 * $ANTLR start idinherit
 * C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:63:1: idinherit : ( NAME | ( NAME COLON NAME ) );
 */
static void
idinherit(pislWalker ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:63:11: ( NAME | ( NAME COLON NAME ) )
            
            ANTLR3_UINT32 alt17;

            alt17=2;


            {
                int LA17_0 = LA(1);
                if ( (LA17_0 == NAME) ) 
                {

                    {
                        int LA17_1 = LA(2);
                        if ( (LA17_1 == COLON) ) 
                        {
                            alt17=2;
                        }
                        else if ( (LA17_1 == 16) ) 
                        {
                            alt17=1;
                        }
                        else 
                        {
                        
                            CONSTRUCTEX();
                            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                            EXCEPTION->message      = (void *)"";
                            EXCEPTION->decisionNum  = 17;
                            EXCEPTION->state        = 1;


                            goto ruleidinheritEx;
                        }
                    }
                }
                else 
                {
                
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 17;
                    EXCEPTION->state        = 0;


                    goto ruleidinheritEx;
                }
            }
            switch (alt17) 
            {
        	case 1:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:63:13: NAME
        	    {
        	         MATCHT(NAME, &FOLLOW_NAME_in_idinherit452); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleidinheritEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:63:20: ( NAME COLON NAME )
        	    {
        	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:63:20: ( NAME COLON NAME )
        	        // C:\\gdev\\iTubras\\tools\\isl\\grammar\\islWalker.g:63:21: NAME COLON NAME
        	        {
        	             MATCHT(NAME, &FOLLOW_NAME_in_idinherit457); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleidinheritEx;
        	            }

        	             MATCHT(COLON, &FOLLOW_COLON_in_idinherit459); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleidinheritEx;
        	            }

        	             MATCHT(NAME, &FOLLOW_NAME_in_idinherit461); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleidinheritEx;
        	            }


        	        }


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleidinheritEx; /* Prevent compiler warnings */
    ruleidinheritEx: ;

    if (HASEXCEPTION())
    {
        PREPORTERROR();
        PRECOVER();
    }

    return ;
}
/* $ANTLR end idinherit */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
